/*** Autogenerated by WIDL 11.7 from drsuapi_min.idl - Do not edit ***/
#include <string.h>

#include "drsuapi.h"

void __RPC_FAR *__RPC_USER midl_user_allocate(size_t cBytes) {
  return ((void __RPC_FAR *)malloc(cBytes));
}

void __RPC_USER midl_user_free(void __RPC_FAR *p) { free(p); }

#define TYPE_FORMAT_STRING_SIZE 1177
#define PROC_FORMAT_STRING_SIZE 981

typedef struct _MIDL_TYPE_FORMAT_STRING {
  short Pad;
  unsigned char Format[TYPE_FORMAT_STRING_SIZE];
} MIDL_TYPE_FORMAT_STRING;

typedef struct _MIDL_PROC_FORMAT_STRING {
  short Pad;
  unsigned char Format[PROC_FORMAT_STRING_SIZE];
} MIDL_PROC_FORMAT_STRING;

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString;
static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString;

/*****************************************************************************
 * drsuapi interface
 */

static const RPC_CLIENT_INTERFACE drsuapi___RpcClientInterface = {
    sizeof(RPC_CLIENT_INTERFACE),
    {{0xe3514235,
      0x4b06,
      0x11d1,
      {0xab, 0x04, 0x00, 0xc0, 0x4f, 0xc2, 0xdc, 0xd2}},
     {4, 0}},
    {{0x8a885d04,
      0x1ceb,
      0x11c9,
      {0x9f, 0xe8, 0x08, 0x00, 0x2b, 0x10, 0x48, 0x60}},
     {2, 0}},
    0,
    0,
    0,
    0,
    0,
    0,
};
RPC_IF_HANDLE drsuapi_v4_0_c_ifspec =
    (RPC_IF_HANDLE)&drsuapi___RpcClientInterface;

static const MIDL_STUB_DESC drsuapi_StubDesc;

static RPC_BINDING_HANDLE drsuapi__MIDL_AutoBindHandle;

ULONG __cdecl IDL_DRSBind(handle_t rpc_handle, GUID *puuidClientDsa,
                          DRS_EXTENSIONS *pextClient,
                          DRS_EXTENSIONS **ppextServer, DRS_HANDLE *phDrs) {
  CLIENT_CALL_RETURN _RetVal;

  _RetVal = NdrClientCall2(&drsuapi_StubDesc,
                           &__MIDL_ProcFormatString.Format[0], rpc_handle,
                           puuidClientDsa, pextClient, ppextServer, phDrs);
  return (ULONG)_RetVal.Simple;
}

ULONG __cdecl IDL_DRSUnbind(DRS_HANDLE *phDrs) {
  CLIENT_CALL_RETURN _RetVal;

  _RetVal = NdrClientCall2(&drsuapi_StubDesc,
                           &__MIDL_ProcFormatString.Format[60], phDrs);
  return (ULONG)_RetVal.Simple;
}

ULONG __cdecl IDL_DRSReplicaSync(DRS_HANDLE hDrs, ULONG dwVersion,
                                 ULONG pmsgIn) {
  CLIENT_CALL_RETURN _RetVal;

  _RetVal =
      NdrClientCall2(&drsuapi_StubDesc, &__MIDL_ProcFormatString.Format[104],
                     hDrs, dwVersion, pmsgIn);
  return (ULONG)_RetVal.Simple;
}

ULONG __cdecl IDL_DRSGetNCChanges(DRS_HANDLE hDrs, ULONG dwInVersion,
                                  DRS_MSG_GETCHGREQ *pmsgIn,
                                  ULONG *pdwOutVersion,
                                  DRS_MSG_GETCHGREPLY *pmsgOut) {
  CLIENT_CALL_RETURN _RetVal;

  _RetVal =
      NdrClientCall2(&drsuapi_StubDesc, &__MIDL_ProcFormatString.Format[160],
                     hDrs, dwInVersion, pmsgIn, pdwOutVersion, pmsgOut);
  return (ULONG)_RetVal.Simple;
}

ULONG __cdecl IDL_DRSUpdateRefs(DRS_HANDLE hDrs, ULONG dwVersion,
                                ULONG pmsgIn) {
  CLIENT_CALL_RETURN _RetVal;

  _RetVal =
      NdrClientCall2(&drsuapi_StubDesc, &__MIDL_ProcFormatString.Format[228],
                     hDrs, dwVersion, pmsgIn);
  return (ULONG)_RetVal.Simple;
}

ULONG __cdecl IDL_DRSReplicaAdd(DRS_HANDLE hDrs, ULONG dwVersion,
                                ULONG pmsgIn) {
  CLIENT_CALL_RETURN _RetVal;

  _RetVal =
      NdrClientCall2(&drsuapi_StubDesc, &__MIDL_ProcFormatString.Format[284],
                     hDrs, dwVersion, pmsgIn);
  return (ULONG)_RetVal.Simple;
}

ULONG __cdecl IDL_DRSReplicaDel(DRS_HANDLE hDrs, ULONG dwVersion,
                                ULONG pmsgIn) {
  CLIENT_CALL_RETURN _RetVal;

  _RetVal =
      NdrClientCall2(&drsuapi_StubDesc, &__MIDL_ProcFormatString.Format[340],
                     hDrs, dwVersion, pmsgIn);
  return (ULONG)_RetVal.Simple;
}

ULONG __cdecl IDL_DRSReplicaModify(DRS_HANDLE hDrs, ULONG dwVersion,
                                   ULONG pmsgIn) {
  CLIENT_CALL_RETURN _RetVal;

  _RetVal =
      NdrClientCall2(&drsuapi_StubDesc, &__MIDL_ProcFormatString.Format[396],
                     hDrs, dwVersion, pmsgIn);
  return (ULONG)_RetVal.Simple;
}

ULONG __cdecl IDL_DRSVerifyNames(DRS_HANDLE hDrs, ULONG dwVersion,
                                 ULONG pmsgIn) {
  CLIENT_CALL_RETURN _RetVal;

  _RetVal =
      NdrClientCall2(&drsuapi_StubDesc, &__MIDL_ProcFormatString.Format[452],
                     hDrs, dwVersion, pmsgIn);
  return (ULONG)_RetVal.Simple;
}

ULONG __cdecl IDL_DRSGetMemberships(DRS_HANDLE hDrs, ULONG dwVersion,
                                    ULONG pmsgIn) {
  CLIENT_CALL_RETURN _RetVal;

  _RetVal =
      NdrClientCall2(&drsuapi_StubDesc, &__MIDL_ProcFormatString.Format[508],
                     hDrs, dwVersion, pmsgIn);
  return (ULONG)_RetVal.Simple;
}

ULONG __cdecl IDL_DRSInterDomainMove(DRS_HANDLE hDrs, ULONG dwVersion,
                                     ULONG pmsgIn) {
  CLIENT_CALL_RETURN _RetVal;

  _RetVal =
      NdrClientCall2(&drsuapi_StubDesc, &__MIDL_ProcFormatString.Format[564],
                     hDrs, dwVersion, pmsgIn);
  return (ULONG)_RetVal.Simple;
}

ULONG __cdecl IDL_DRSGetNT4ChangeLog(DRS_HANDLE hDrs, ULONG dwVersion,
                                     ULONG pmsgIn) {
  CLIENT_CALL_RETURN _RetVal;

  _RetVal =
      NdrClientCall2(&drsuapi_StubDesc, &__MIDL_ProcFormatString.Format[620],
                     hDrs, dwVersion, pmsgIn);
  return (ULONG)_RetVal.Simple;
}

ULONG __cdecl IDL_DRSCrackNames(DRS_HANDLE hDrs, ULONG dwInVersion,
                                DRS_MSG_CRACKREQ *pmsgIn, ULONG *pdwOutVersion,
                                DRS_MSG_CRACKREPLY *pmsgOut) {
  CLIENT_CALL_RETURN _RetVal;

  _RetVal =
      NdrClientCall2(&drsuapi_StubDesc, &__MIDL_ProcFormatString.Format[676],
                     hDrs, dwInVersion, pmsgIn, pdwOutVersion, pmsgOut);
  return (ULONG)_RetVal.Simple;
}

ULONG __cdecl IDL_DRSWriteSPN(DRS_HANDLE hDrs, ULONG dwVersion, ULONG pmsgIn) {
  CLIENT_CALL_RETURN _RetVal;

  _RetVal =
      NdrClientCall2(&drsuapi_StubDesc, &__MIDL_ProcFormatString.Format[744],
                     hDrs, dwVersion, pmsgIn);
  return (ULONG)_RetVal.Simple;
}

ULONG __cdecl IDL_DRSRemoveDsServer(DRS_HANDLE hDrs, ULONG dwVersion,
                                    ULONG pmsgIn) {
  CLIENT_CALL_RETURN _RetVal;

  _RetVal =
      NdrClientCall2(&drsuapi_StubDesc, &__MIDL_ProcFormatString.Format[800],
                     hDrs, dwVersion, pmsgIn);
  return (ULONG)_RetVal.Simple;
}

ULONG __cdecl IDL_DRSRemoveDsDomain(DRS_HANDLE hDrs, ULONG dwVersion,
                                    ULONG pmsgIn) {
  CLIENT_CALL_RETURN _RetVal;

  _RetVal =
      NdrClientCall2(&drsuapi_StubDesc, &__MIDL_ProcFormatString.Format[856],
                     hDrs, dwVersion, pmsgIn);
  return (ULONG)_RetVal.Simple;
}

ULONG __cdecl IDL_DRSDomainControllerInfo(DRS_HANDLE hDrs, ULONG dwInVersion,
                                          DRS_MSG_DCINFOREQ *pmsgIn,
                                          ULONG *pdwOutVersion,
                                          DRS_MSG_DCINFOREPLY *pmsgOut) {
  CLIENT_CALL_RETURN _RetVal;

  _RetVal =
      NdrClientCall2(&drsuapi_StubDesc, &__MIDL_ProcFormatString.Format[912],
                     hDrs, dwInVersion, pmsgIn, pdwOutVersion, pmsgOut);
  return (ULONG)_RetVal.Simple;
}

#if !defined(__RPC_WIN64__)
#error Invalid build platform for this stub.
#endif

static const MIDL_STUB_DESC drsuapi_StubDesc = {
    (void *)&drsuapi___RpcClientInterface,
    MIDL_user_allocate,
    MIDL_user_free,
    {
        &drsuapi__MIDL_AutoBindHandle,
    },
    0,
    0,
    0,
    0,
    __MIDL_TypeFormatString.Format,
    1,       /* -error bounds_check flag */
    0x50002, /* Ndr library version */
    0,
    0x50200ca, /* MIDL Version 5.2.202 */
    0,
    0,
    0, /* notify & notify_flag routine table */
    1, /* Flags */
    0, /* Reserved3 */
    0, /* Reserved4 */
    0  /* Reserved5 */
};

static const MIDL_PROC_FORMAT_STRING __MIDL_ProcFormatString = {
    0,
    {      /* 0 (procedure drsuapi::IDL_DRSBind) */
     0x00, /* explicit handle */
     0x48, NdrFcLong(0x0), NdrFcShort(0x0), /* method 0 */
     NdrFcShort(0x30),                      /* stack size = 48 */
     0x32,                                  /* FC_BIND_PRIMITIVE */
     0x00, NdrFcShort(0x0),                 /* stack offset = 0 */
     NdrFcShort(0x1c),                      /* client buffer = 28 */
     NdrFcShort(0x20),                      /* server buffer = 32 */
     0x47, 0x05,                            /* 5 params */
     0x0a, 0x01, NdrFcShort(0x0), NdrFcShort(0x0), NdrFcShort(0x0),
     NdrFcShort(0x0),
     /* 30 (parameter puuidClientDsa) */
     NdrFcShort(0xa),    /* flags: must free, in */
     NdrFcShort(0x8),    /* stack offset = 8 */
     NdrFcShort(0x14),   /* type offset = 20 */
                         /* 36 (parameter pextClient) */
     NdrFcShort(0xb),    /* flags: must size, must free, in */
     NdrFcShort(0x10),   /* stack offset = 16 */
     NdrFcShort(0x2c),   /* type offset = 44 */
                         /* 42 (parameter ppextServer) */
     NdrFcShort(0x2013), /* flags: must size, must free, out, srv size=8 */
     NdrFcShort(0x18),   /* stack offset = 24 */
     NdrFcShort(0x34),   /* type offset = 52 */
                         /* 48 (parameter phDrs) */
     NdrFcShort(0x110),  /* flags: out, simple ref */
     NdrFcShort(0x20),   /* stack offset = 32 */
     NdrFcShort(0x3c),   /* type offset = 60 */
                         /* 54 (return value) */
     NdrFcShort(0x70),   /* flags: out, return, base type */
     NdrFcShort(0x28),   /* stack offset = 40 */
     0x08,               /* FC_LONG */
     0x0,
     /* 60 (procedure drsuapi::IDL_DRSUnbind) */
     0x00,                                  /* explicit handle */
     0x48, NdrFcLong(0x0), NdrFcShort(0x1), /* method 1 */
     NdrFcShort(0x10),                      /* stack size = 16 */
     0x30,                                  /* FC_BIND_CONTEXT */
     0xe0, NdrFcShort(0x0),                 /* stack offset = 0 */
     0x00, 0x00,                            /* param 0 */
     NdrFcShort(0x18),                      /* client buffer = 24 */
     NdrFcShort(0x20),                      /* server buffer = 32 */
     0x44, 0x02,                            /* 2 params */
     0x0a, 0x01, NdrFcShort(0x0), NdrFcShort(0x0), NdrFcShort(0x0),
     NdrFcShort(0x0),
     /* 92 (parameter phDrs) */
     NdrFcShort(0x118), /* flags: in, out, simple ref */
     NdrFcShort(0x0),   /* stack offset = 0 */
     NdrFcShort(0x44),  /* type offset = 68 */
                        /* 98 (return value) */
     NdrFcShort(0x70),  /* flags: out, return, base type */
     NdrFcShort(0x8),   /* stack offset = 8 */
     0x08,              /* FC_LONG */
     0x0,
     /* 104 (procedure drsuapi::IDL_DRSReplicaSync) */
     0x00,                                  /* explicit handle */
     0x48, NdrFcLong(0x0), NdrFcShort(0x2), /* method 2 */
     NdrFcShort(0x20),                      /* stack size = 32 */
     0x30,                                  /* FC_BIND_CONTEXT */
     0x41, NdrFcShort(0x0),                 /* stack offset = 0 */
     0x00, 0x00,                            /* param 0 */
     NdrFcShort(0x28),                      /* client buffer = 40 */
     NdrFcShort(0x8),                       /* server buffer = 8 */
     0x44, 0x04,                            /* 4 params */
     0x0a, 0x01, NdrFcShort(0x0), NdrFcShort(0x0), NdrFcShort(0x0),
     NdrFcShort(0x0),
     /* 136 (parameter hDrs) */
     NdrFcShort(0x8),  /* flags: in */
     NdrFcShort(0x0),  /* stack offset = 0 */
     NdrFcShort(0x48), /* type offset = 72 */
                       /* 142 (parameter dwVersion) */
     NdrFcShort(0x48), /* flags: in, base type */
     NdrFcShort(0x8),  /* stack offset = 8 */
     0x08,             /* FC_LONG */
     0x0,
     /* 148 (parameter pmsgIn) */
     NdrFcShort(0x48), /* flags: in, base type */
     NdrFcShort(0x10), /* stack offset = 16 */
     0x08,             /* FC_LONG */
     0x0,
     /* 154 (return value) */
     NdrFcShort(0x70), /* flags: out, return, base type */
     NdrFcShort(0x18), /* stack offset = 24 */
     0x08,             /* FC_LONG */
     0x0,
     /* 160 (procedure drsuapi::IDL_DRSGetNCChanges) */
     0x00,                                  /* explicit handle */
     0x48, NdrFcLong(0x0), NdrFcShort(0x3), /* method 3 */
     NdrFcShort(0x30),                      /* stack size = 48 */
     0x30,                                  /* FC_BIND_CONTEXT */
     0x41, NdrFcShort(0x0),                 /* stack offset = 0 */
     0x00, 0x00,                            /* param 0 */
     NdrFcShort(0x20),                      /* client buffer = 32 */
     NdrFcShort(0x10),                      /* server buffer = 16 */
     0x47, 0x06,                            /* 6 params */
     0x0a, 0x01, NdrFcShort(0x0), NdrFcShort(0x0), NdrFcShort(0x0),
     NdrFcShort(0x0),
     /* 192 (parameter hDrs) */
     NdrFcShort(0x8),  /* flags: in */
     NdrFcShort(0x0),  /* stack offset = 0 */
     NdrFcShort(0x4c), /* type offset = 76 */
                       /* 198 (parameter dwInVersion) */
     NdrFcShort(0x48), /* flags: in, base type */
     NdrFcShort(0x8),  /* stack offset = 8 */
     0x08,             /* FC_LONG */
     0x0,
     /* 204 (parameter pmsgIn) */
     NdrFcShort(0x10b),  /* flags: must size, must free, in, simple ref */
     NdrFcShort(0x10),   /* stack offset = 16 */
     NdrFcShort(0x148),  /* type offset = 328 */
                         /* 210 (parameter pdwOutVersion) */
     NdrFcShort(0x2150), /* flags: out, base type, simple ref, srv size=8 */
     NdrFcShort(0x18),   /* stack offset = 24 */
     0x09,               /* FC_ULONG */
     0x0,
     /* 216 (parameter pmsgOut) */
     NdrFcShort(0x113), /* flags: must size, must free, out, simple ref */
     NdrFcShort(0x20),  /* stack offset = 32 */
     NdrFcShort(0x2ec), /* type offset = 748 */
                        /* 222 (return value) */
     NdrFcShort(0x70),  /* flags: out, return, base type */
     NdrFcShort(0x28),  /* stack offset = 40 */
     0x08,              /* FC_LONG */
     0x0,
     /* 228 (procedure drsuapi::IDL_DRSUpdateRefs) */
     0x00,                                  /* explicit handle */
     0x48, NdrFcLong(0x0), NdrFcShort(0x4), /* method 4 */
     NdrFcShort(0x20),                      /* stack size = 32 */
     0x30,                                  /* FC_BIND_CONTEXT */
     0x41, NdrFcShort(0x0),                 /* stack offset = 0 */
     0x00, 0x00,                            /* param 0 */
     NdrFcShort(0x28),                      /* client buffer = 40 */
     NdrFcShort(0x8),                       /* server buffer = 8 */
     0x44, 0x04,                            /* 4 params */
     0x0a, 0x01, NdrFcShort(0x0), NdrFcShort(0x0), NdrFcShort(0x0),
     NdrFcShort(0x0),
     /* 260 (parameter hDrs) */
     NdrFcShort(0x8),   /* flags: in */
     NdrFcShort(0x0),   /* stack offset = 0 */
     NdrFcShort(0x2fe), /* type offset = 766 */
                        /* 266 (parameter dwVersion) */
     NdrFcShort(0x48),  /* flags: in, base type */
     NdrFcShort(0x8),   /* stack offset = 8 */
     0x08,              /* FC_LONG */
     0x0,
     /* 272 (parameter pmsgIn) */
     NdrFcShort(0x48), /* flags: in, base type */
     NdrFcShort(0x10), /* stack offset = 16 */
     0x08,             /* FC_LONG */
     0x0,
     /* 278 (return value) */
     NdrFcShort(0x70), /* flags: out, return, base type */
     NdrFcShort(0x18), /* stack offset = 24 */
     0x08,             /* FC_LONG */
     0x0,
     /* 284 (procedure drsuapi::IDL_DRSReplicaAdd) */
     0x00,                                  /* explicit handle */
     0x48, NdrFcLong(0x0), NdrFcShort(0x5), /* method 5 */
     NdrFcShort(0x20),                      /* stack size = 32 */
     0x30,                                  /* FC_BIND_CONTEXT */
     0x41, NdrFcShort(0x0),                 /* stack offset = 0 */
     0x00, 0x00,                            /* param 0 */
     NdrFcShort(0x28),                      /* client buffer = 40 */
     NdrFcShort(0x8),                       /* server buffer = 8 */
     0x44, 0x04,                            /* 4 params */
     0x0a, 0x01, NdrFcShort(0x0), NdrFcShort(0x0), NdrFcShort(0x0),
     NdrFcShort(0x0),
     /* 316 (parameter hDrs) */
     NdrFcShort(0x8),   /* flags: in */
     NdrFcShort(0x0),   /* stack offset = 0 */
     NdrFcShort(0x302), /* type offset = 770 */
                        /* 322 (parameter dwVersion) */
     NdrFcShort(0x48),  /* flags: in, base type */
     NdrFcShort(0x8),   /* stack offset = 8 */
     0x08,              /* FC_LONG */
     0x0,
     /* 328 (parameter pmsgIn) */
     NdrFcShort(0x48), /* flags: in, base type */
     NdrFcShort(0x10), /* stack offset = 16 */
     0x08,             /* FC_LONG */
     0x0,
     /* 334 (return value) */
     NdrFcShort(0x70), /* flags: out, return, base type */
     NdrFcShort(0x18), /* stack offset = 24 */
     0x08,             /* FC_LONG */
     0x0,
     /* 340 (procedure drsuapi::IDL_DRSReplicaDel) */
     0x00,                                  /* explicit handle */
     0x48, NdrFcLong(0x0), NdrFcShort(0x6), /* method 6 */
     NdrFcShort(0x20),                      /* stack size = 32 */
     0x30,                                  /* FC_BIND_CONTEXT */
     0x41, NdrFcShort(0x0),                 /* stack offset = 0 */
     0x00, 0x00,                            /* param 0 */
     NdrFcShort(0x28),                      /* client buffer = 40 */
     NdrFcShort(0x8),                       /* server buffer = 8 */
     0x44, 0x04,                            /* 4 params */
     0x0a, 0x01, NdrFcShort(0x0), NdrFcShort(0x0), NdrFcShort(0x0),
     NdrFcShort(0x0),
     /* 372 (parameter hDrs) */
     NdrFcShort(0x8),   /* flags: in */
     NdrFcShort(0x0),   /* stack offset = 0 */
     NdrFcShort(0x306), /* type offset = 774 */
                        /* 378 (parameter dwVersion) */
     NdrFcShort(0x48),  /* flags: in, base type */
     NdrFcShort(0x8),   /* stack offset = 8 */
     0x08,              /* FC_LONG */
     0x0,
     /* 384 (parameter pmsgIn) */
     NdrFcShort(0x48), /* flags: in, base type */
     NdrFcShort(0x10), /* stack offset = 16 */
     0x08,             /* FC_LONG */
     0x0,
     /* 390 (return value) */
     NdrFcShort(0x70), /* flags: out, return, base type */
     NdrFcShort(0x18), /* stack offset = 24 */
     0x08,             /* FC_LONG */
     0x0,
     /* 396 (procedure drsuapi::IDL_DRSReplicaModify) */
     0x00,                                  /* explicit handle */
     0x48, NdrFcLong(0x0), NdrFcShort(0x7), /* method 7 */
     NdrFcShort(0x20),                      /* stack size = 32 */
     0x30,                                  /* FC_BIND_CONTEXT */
     0x41, NdrFcShort(0x0),                 /* stack offset = 0 */
     0x00, 0x00,                            /* param 0 */
     NdrFcShort(0x28),                      /* client buffer = 40 */
     NdrFcShort(0x8),                       /* server buffer = 8 */
     0x44, 0x04,                            /* 4 params */
     0x0a, 0x01, NdrFcShort(0x0), NdrFcShort(0x0), NdrFcShort(0x0),
     NdrFcShort(0x0),
     /* 428 (parameter hDrs) */
     NdrFcShort(0x8),   /* flags: in */
     NdrFcShort(0x0),   /* stack offset = 0 */
     NdrFcShort(0x30a), /* type offset = 778 */
                        /* 434 (parameter dwVersion) */
     NdrFcShort(0x48),  /* flags: in, base type */
     NdrFcShort(0x8),   /* stack offset = 8 */
     0x08,              /* FC_LONG */
     0x0,
     /* 440 (parameter pmsgIn) */
     NdrFcShort(0x48), /* flags: in, base type */
     NdrFcShort(0x10), /* stack offset = 16 */
     0x08,             /* FC_LONG */
     0x0,
     /* 446 (return value) */
     NdrFcShort(0x70), /* flags: out, return, base type */
     NdrFcShort(0x18), /* stack offset = 24 */
     0x08,             /* FC_LONG */
     0x0,
     /* 452 (procedure drsuapi::IDL_DRSVerifyNames) */
     0x00,                                  /* explicit handle */
     0x48, NdrFcLong(0x0), NdrFcShort(0x8), /* method 8 */
     NdrFcShort(0x20),                      /* stack size = 32 */
     0x30,                                  /* FC_BIND_CONTEXT */
     0x41, NdrFcShort(0x0),                 /* stack offset = 0 */
     0x00, 0x00,                            /* param 0 */
     NdrFcShort(0x28),                      /* client buffer = 40 */
     NdrFcShort(0x8),                       /* server buffer = 8 */
     0x44, 0x04,                            /* 4 params */
     0x0a, 0x01, NdrFcShort(0x0), NdrFcShort(0x0), NdrFcShort(0x0),
     NdrFcShort(0x0),
     /* 484 (parameter hDrs) */
     NdrFcShort(0x8),   /* flags: in */
     NdrFcShort(0x0),   /* stack offset = 0 */
     NdrFcShort(0x30e), /* type offset = 782 */
                        /* 490 (parameter dwVersion) */
     NdrFcShort(0x48),  /* flags: in, base type */
     NdrFcShort(0x8),   /* stack offset = 8 */
     0x08,              /* FC_LONG */
     0x0,
     /* 496 (parameter pmsgIn) */
     NdrFcShort(0x48), /* flags: in, base type */
     NdrFcShort(0x10), /* stack offset = 16 */
     0x08,             /* FC_LONG */
     0x0,
     /* 502 (return value) */
     NdrFcShort(0x70), /* flags: out, return, base type */
     NdrFcShort(0x18), /* stack offset = 24 */
     0x08,             /* FC_LONG */
     0x0,
     /* 508 (procedure drsuapi::IDL_DRSGetMemberships) */
     0x00,                                  /* explicit handle */
     0x48, NdrFcLong(0x0), NdrFcShort(0x9), /* method 9 */
     NdrFcShort(0x20),                      /* stack size = 32 */
     0x30,                                  /* FC_BIND_CONTEXT */
     0x41, NdrFcShort(0x0),                 /* stack offset = 0 */
     0x00, 0x00,                            /* param 0 */
     NdrFcShort(0x28),                      /* client buffer = 40 */
     NdrFcShort(0x8),                       /* server buffer = 8 */
     0x44, 0x04,                            /* 4 params */
     0x0a, 0x01, NdrFcShort(0x0), NdrFcShort(0x0), NdrFcShort(0x0),
     NdrFcShort(0x0),
     /* 540 (parameter hDrs) */
     NdrFcShort(0x8),   /* flags: in */
     NdrFcShort(0x0),   /* stack offset = 0 */
     NdrFcShort(0x312), /* type offset = 786 */
                        /* 546 (parameter dwVersion) */
     NdrFcShort(0x48),  /* flags: in, base type */
     NdrFcShort(0x8),   /* stack offset = 8 */
     0x08,              /* FC_LONG */
     0x0,
     /* 552 (parameter pmsgIn) */
     NdrFcShort(0x48), /* flags: in, base type */
     NdrFcShort(0x10), /* stack offset = 16 */
     0x08,             /* FC_LONG */
     0x0,
     /* 558 (return value) */
     NdrFcShort(0x70), /* flags: out, return, base type */
     NdrFcShort(0x18), /* stack offset = 24 */
     0x08,             /* FC_LONG */
     0x0,
     /* 564 (procedure drsuapi::IDL_DRSInterDomainMove) */
     0x00,                                  /* explicit handle */
     0x48, NdrFcLong(0x0), NdrFcShort(0xa), /* method 10 */
     NdrFcShort(0x20),                      /* stack size = 32 */
     0x30,                                  /* FC_BIND_CONTEXT */
     0x41, NdrFcShort(0x0),                 /* stack offset = 0 */
     0x00, 0x00,                            /* param 0 */
     NdrFcShort(0x28),                      /* client buffer = 40 */
     NdrFcShort(0x8),                       /* server buffer = 8 */
     0x44, 0x04,                            /* 4 params */
     0x0a, 0x01, NdrFcShort(0x0), NdrFcShort(0x0), NdrFcShort(0x0),
     NdrFcShort(0x0),
     /* 596 (parameter hDrs) */
     NdrFcShort(0x8),   /* flags: in */
     NdrFcShort(0x0),   /* stack offset = 0 */
     NdrFcShort(0x316), /* type offset = 790 */
                        /* 602 (parameter dwVersion) */
     NdrFcShort(0x48),  /* flags: in, base type */
     NdrFcShort(0x8),   /* stack offset = 8 */
     0x08,              /* FC_LONG */
     0x0,
     /* 608 (parameter pmsgIn) */
     NdrFcShort(0x48), /* flags: in, base type */
     NdrFcShort(0x10), /* stack offset = 16 */
     0x08,             /* FC_LONG */
     0x0,
     /* 614 (return value) */
     NdrFcShort(0x70), /* flags: out, return, base type */
     NdrFcShort(0x18), /* stack offset = 24 */
     0x08,             /* FC_LONG */
     0x0,
     /* 620 (procedure drsuapi::IDL_DRSGetNT4ChangeLog) */
     0x00,                                  /* explicit handle */
     0x48, NdrFcLong(0x0), NdrFcShort(0xb), /* method 11 */
     NdrFcShort(0x20),                      /* stack size = 32 */
     0x30,                                  /* FC_BIND_CONTEXT */
     0x41, NdrFcShort(0x0),                 /* stack offset = 0 */
     0x00, 0x00,                            /* param 0 */
     NdrFcShort(0x28),                      /* client buffer = 40 */
     NdrFcShort(0x8),                       /* server buffer = 8 */
     0x44, 0x04,                            /* 4 params */
     0x0a, 0x01, NdrFcShort(0x0), NdrFcShort(0x0), NdrFcShort(0x0),
     NdrFcShort(0x0),
     /* 652 (parameter hDrs) */
     NdrFcShort(0x8),   /* flags: in */
     NdrFcShort(0x0),   /* stack offset = 0 */
     NdrFcShort(0x31a), /* type offset = 794 */
                        /* 658 (parameter dwVersion) */
     NdrFcShort(0x48),  /* flags: in, base type */
     NdrFcShort(0x8),   /* stack offset = 8 */
     0x08,              /* FC_LONG */
     0x0,
     /* 664 (parameter pmsgIn) */
     NdrFcShort(0x48), /* flags: in, base type */
     NdrFcShort(0x10), /* stack offset = 16 */
     0x08,             /* FC_LONG */
     0x0,
     /* 670 (return value) */
     NdrFcShort(0x70), /* flags: out, return, base type */
     NdrFcShort(0x18), /* stack offset = 24 */
     0x08,             /* FC_LONG */
     0x0,
     /* 676 (procedure drsuapi::IDL_DRSCrackNames) */
     0x00,                                  /* explicit handle */
     0x48, NdrFcLong(0x0), NdrFcShort(0xc), /* method 12 */
     NdrFcShort(0x30),                      /* stack size = 48 */
     0x30,                                  /* FC_BIND_CONTEXT */
     0x41, NdrFcShort(0x0),                 /* stack offset = 0 */
     0x00, 0x00,                            /* param 0 */
     NdrFcShort(0x20),                      /* client buffer = 32 */
     NdrFcShort(0x10),                      /* server buffer = 16 */
     0x47, 0x06,                            /* 6 params */
     0x0a, 0x01, NdrFcShort(0x0), NdrFcShort(0x0), NdrFcShort(0x0),
     NdrFcShort(0x0),
     /* 708 (parameter hDrs) */
     NdrFcShort(0x8),   /* flags: in */
     NdrFcShort(0x0),   /* stack offset = 0 */
     NdrFcShort(0x31e), /* type offset = 798 */
                        /* 714 (parameter dwInVersion) */
     NdrFcShort(0x48),  /* flags: in, base type */
     NdrFcShort(0x8),   /* stack offset = 8 */
     0x08,              /* FC_LONG */
     0x0,
     /* 720 (parameter pmsgIn) */
     NdrFcShort(0x10b),  /* flags: must size, must free, in, simple ref */
     NdrFcShort(0x10),   /* stack offset = 16 */
     NdrFcShort(0x350),  /* type offset = 848 */
                         /* 726 (parameter pdwOutVersion) */
     NdrFcShort(0x2150), /* flags: out, base type, simple ref, srv size=8 */
     NdrFcShort(0x18),   /* stack offset = 24 */
     0x09,               /* FC_ULONG */
     0x0,
     /* 732 (parameter pmsgOut) */
     NdrFcShort(0x4113), /* flags: must size, must free, out, simple ref, srv
                            size=16 */
     NdrFcShort(0x20),   /* stack offset = 32 */
     NdrFcShort(0x3b8),  /* type offset = 952 */
                         /* 738 (return value) */
     NdrFcShort(0x70),   /* flags: out, return, base type */
     NdrFcShort(0x28),   /* stack offset = 40 */
     0x08,               /* FC_LONG */
     0x0,
     /* 744 (procedure drsuapi::IDL_DRSWriteSPN) */
     0x00,                                  /* explicit handle */
     0x48, NdrFcLong(0x0), NdrFcShort(0xd), /* method 13 */
     NdrFcShort(0x20),                      /* stack size = 32 */
     0x30,                                  /* FC_BIND_CONTEXT */
     0x41, NdrFcShort(0x0),                 /* stack offset = 0 */
     0x00, 0x00,                            /* param 0 */
     NdrFcShort(0x28),                      /* client buffer = 40 */
     NdrFcShort(0x8),                       /* server buffer = 8 */
     0x44, 0x04,                            /* 4 params */
     0x0a, 0x01, NdrFcShort(0x0), NdrFcShort(0x0), NdrFcShort(0x0),
     NdrFcShort(0x0),
     /* 776 (parameter hDrs) */
     NdrFcShort(0x8),   /* flags: in */
     NdrFcShort(0x0),   /* stack offset = 0 */
     NdrFcShort(0x3ca), /* type offset = 970 */
                        /* 782 (parameter dwVersion) */
     NdrFcShort(0x48),  /* flags: in, base type */
     NdrFcShort(0x8),   /* stack offset = 8 */
     0x08,              /* FC_LONG */
     0x0,
     /* 788 (parameter pmsgIn) */
     NdrFcShort(0x48), /* flags: in, base type */
     NdrFcShort(0x10), /* stack offset = 16 */
     0x08,             /* FC_LONG */
     0x0,
     /* 794 (return value) */
     NdrFcShort(0x70), /* flags: out, return, base type */
     NdrFcShort(0x18), /* stack offset = 24 */
     0x08,             /* FC_LONG */
     0x0,
     /* 800 (procedure drsuapi::IDL_DRSRemoveDsServer) */
     0x00,                                  /* explicit handle */
     0x48, NdrFcLong(0x0), NdrFcShort(0xe), /* method 14 */
     NdrFcShort(0x20),                      /* stack size = 32 */
     0x30,                                  /* FC_BIND_CONTEXT */
     0x41, NdrFcShort(0x0),                 /* stack offset = 0 */
     0x00, 0x00,                            /* param 0 */
     NdrFcShort(0x28),                      /* client buffer = 40 */
     NdrFcShort(0x8),                       /* server buffer = 8 */
     0x44, 0x04,                            /* 4 params */
     0x0a, 0x01, NdrFcShort(0x0), NdrFcShort(0x0), NdrFcShort(0x0),
     NdrFcShort(0x0),
     /* 832 (parameter hDrs) */
     NdrFcShort(0x8),   /* flags: in */
     NdrFcShort(0x0),   /* stack offset = 0 */
     NdrFcShort(0x3ce), /* type offset = 974 */
                        /* 838 (parameter dwVersion) */
     NdrFcShort(0x48),  /* flags: in, base type */
     NdrFcShort(0x8),   /* stack offset = 8 */
     0x08,              /* FC_LONG */
     0x0,
     /* 844 (parameter pmsgIn) */
     NdrFcShort(0x48), /* flags: in, base type */
     NdrFcShort(0x10), /* stack offset = 16 */
     0x08,             /* FC_LONG */
     0x0,
     /* 850 (return value) */
     NdrFcShort(0x70), /* flags: out, return, base type */
     NdrFcShort(0x18), /* stack offset = 24 */
     0x08,             /* FC_LONG */
     0x0,
     /* 856 (procedure drsuapi::IDL_DRSRemoveDsDomain) */
     0x00,                                  /* explicit handle */
     0x48, NdrFcLong(0x0), NdrFcShort(0xf), /* method 15 */
     NdrFcShort(0x20),                      /* stack size = 32 */
     0x30,                                  /* FC_BIND_CONTEXT */
     0x41, NdrFcShort(0x0),                 /* stack offset = 0 */
     0x00, 0x00,                            /* param 0 */
     NdrFcShort(0x28),                      /* client buffer = 40 */
     NdrFcShort(0x8),                       /* server buffer = 8 */
     0x44, 0x04,                            /* 4 params */
     0x0a, 0x01, NdrFcShort(0x0), NdrFcShort(0x0), NdrFcShort(0x0),
     NdrFcShort(0x0),
     /* 888 (parameter hDrs) */
     NdrFcShort(0x8),   /* flags: in */
     NdrFcShort(0x0),   /* stack offset = 0 */
     NdrFcShort(0x3d2), /* type offset = 978 */
                        /* 894 (parameter dwVersion) */
     NdrFcShort(0x48),  /* flags: in, base type */
     NdrFcShort(0x8),   /* stack offset = 8 */
     0x08,              /* FC_LONG */
     0x0,
     /* 900 (parameter pmsgIn) */
     NdrFcShort(0x48), /* flags: in, base type */
     NdrFcShort(0x10), /* stack offset = 16 */
     0x08,             /* FC_LONG */
     0x0,
     /* 906 (return value) */
     NdrFcShort(0x70), /* flags: out, return, base type */
     NdrFcShort(0x18), /* stack offset = 24 */
     0x08,             /* FC_LONG */
     0x0,
     /* 912 (procedure drsuapi::IDL_DRSDomainControllerInfo) */
     0x00,                                   /* explicit handle */
     0x48, NdrFcLong(0x0), NdrFcShort(0x10), /* method 16 */
     NdrFcShort(0x30),                       /* stack size = 48 */
     0x30,                                   /* FC_BIND_CONTEXT */
     0x41, NdrFcShort(0x0),                  /* stack offset = 0 */
     0x00, 0x00,                             /* param 0 */
     NdrFcShort(0x20),                       /* client buffer = 32 */
     NdrFcShort(0x10),                       /* server buffer = 16 */
     0x47, 0x06,                             /* 6 params */
     0x0a, 0x01, NdrFcShort(0x0), NdrFcShort(0x0), NdrFcShort(0x0),
     NdrFcShort(0x0),
     /* 944 (parameter hDrs) */
     NdrFcShort(0x8),   /* flags: in */
     NdrFcShort(0x0),   /* stack offset = 0 */
     NdrFcShort(0x3d6), /* type offset = 982 */
                        /* 950 (parameter dwInVersion) */
     NdrFcShort(0x48),  /* flags: in, base type */
     NdrFcShort(0x8),   /* stack offset = 8 */
     0x08,              /* FC_LONG */
     0x0,
     /* 956 (parameter pmsgIn) */
     NdrFcShort(0x10b),  /* flags: must size, must free, in, simple ref */
     NdrFcShort(0x10),   /* stack offset = 16 */
     NdrFcShort(0x3ee),  /* type offset = 1006 */
                         /* 962 (parameter pdwOutVersion) */
     NdrFcShort(0x2150), /* flags: out, base type, simple ref, srv size=8 */
     NdrFcShort(0x18),   /* stack offset = 24 */
     0x09,               /* FC_ULONG */
     0x0,
     /* 968 (parameter pmsgOut) */
     NdrFcShort(0x6113), /* flags: must size, must free, out, simple ref, srv
                            size=24 */
     NdrFcShort(0x20),   /* stack offset = 32 */
     NdrFcShort(0x486),  /* type offset = 1158 */
                         /* 974 (return value) */
     NdrFcShort(0x70),   /* flags: out, return, base type */
     NdrFcShort(0x28),   /* stack offset = 40 */
     0x08,               /* FC_LONG */
     0x0, 0x0}};

static const MIDL_TYPE_FORMAT_STRING __MIDL_TypeFormatString = {
    0,
    {NdrFcShort(0x0),
     /* 2 (byte[8]) */
     0x1d,                    /* FC_SMFARRAY */
     0x0,                     /* 0 */
     NdrFcShort(0x8),         /* 8 */
     0x01,                    /* FC_BYTE */
     0x5b,                    /* FC_END */
                              /* 8 (GUID) */
     0x15,                    /* FC_STRUCT */
     0x3,                     /* 3 */
     NdrFcShort(0x10),        /* 16 */
     0x08,                    /* FC_LONG */
     0x06,                    /* FC_SHORT */
     0x06,                    /* FC_SHORT */
     0x4c,                    /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xfff1), /* Offset= -15 (2) */
     0x5b,                    /* FC_END */
                              /* 20 (GUID *) */
     0x12, 0x0,               /* FC_UP */
     NdrFcShort(0xfff2),      /* Offset= -14 (8) */
                              /* 24 (unsigned char[]) */
     0x1b,                    /* FC_CARRAY */
     0x0,                     /* 0 */
     NdrFcShort(0x1),         /* 1 */
     0x9,                     /* Corr desc: field cb, FC_ULONG */
     0x0,                     /* no operators */
     NdrFcShort(0xfffc),      /* offset = -4 */
     NdrFcShort(0x1), 0x02,   /* FC_CHAR */
     0x5b,                    /* FC_END */
                              /* 36 (DRS_EXTENSIONS) */
     0x17,                    /* FC_CSTRUCT */
     0x3,                     /* 3 */
     NdrFcShort(0x4),         /* 4 */
     NdrFcShort(0xfff0),      /* Offset= -16 (24) */
     0x08,                    /* FC_LONG */
     0x5b,                    /* FC_END */
                              /* 44 (DRS_EXTENSIONS *) */
     0x12, 0x0,               /* FC_UP */
     NdrFcShort(0xfff6),      /* Offset= -10 (36) */
                              /* 48 (DRS_EXTENSIONS *) */
     0x12, 0x0,               /* FC_UP */
     NdrFcShort(0xfff2),      /* Offset= -14 (36) */
                              /* 52 (DRS_EXTENSIONS **) */
     0x11, 0x14,              /* FC_RP [allocated_on_stack] [pointer_deref] */
     NdrFcShort(0xfffa),      /* Offset= -6 (48) */
                              /* 56 (DRS_HANDLE *) */
     0x11, 0x0,               /* FC_RP */
     NdrFcShort(0x2),         /* Offset= 2 (60) */
                              /* 60 */
     0x30,                    /* FC_BIND_CONTEXT */
     0xa0,                    /* Context flags: out, via ptr, */
     0x0,                     /* rundown routine */
     0,                       /* FIXME: param num */
                              /* 64 (DRS_HANDLE *) */
     0x11, 0x0,               /* FC_RP */
     NdrFcShort(0x2),         /* Offset= 2 (68) */
                              /* 68 */
     0x30,                    /* FC_BIND_CONTEXT */
     0xe0,                    /* Context flags: out, in, via ptr, */
     0x0,                     /* rundown routine */
     0,                       /* FIXME: param num */
                              /* 72 (DRS_HANDLE) */
     0x30,                    /* FC_BIND_CONTEXT */
     0x41,                    /* Context flags: can't be null, in, */
     0x0,                     /* rundown routine */
     0,                       /* FIXME: param num */
                              /* 76 (DRS_HANDLE) */
     0x30,                    /* FC_BIND_CONTEXT */
     0x41,                    /* Context flags: can't be null, in, */
     0x0,                     /* rundown routine */
     0,                       /* FIXME: param num */
                              /* 80 (unsigned char[28]) */
     0x1d,                    /* FC_SMFARRAY */
     0x0,                     /* 0 */
     NdrFcShort(0x1c),        /* 28 */
     0x02,                    /* FC_CHAR */
     0x5b,                    /* FC_END */
                              /* 86 (NT4SID) */
     0x15,                    /* FC_STRUCT */
     0x0,                     /* 0 */
     NdrFcShort(0x1c),        /* 28 */
     0x4c,                    /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xfff4), /* Offset= -12 (80) */
     0x5c,                    /* FC_PAD */
     0x5b,                    /* FC_END */
                              /* 96 (wchar_t[]) */
     0x1b,                    /* FC_CARRAY */
     0x1,                     /* 1 */
     NdrFcShort(0x2),         /* 2 */
     0x9,                     /* Corr desc: field NameLen, FC_ULONG */
     0x57,                    /* FC_ADD_1 */
     NdrFcShort(0xfffc),      /* offset = -4 */
     NdrFcShort(0x1), 0x05,   /* FC_WCHAR */
     0x5b,                    /* FC_END */
                              /* 108 (DSNAME) */
     0x17,                    /* FC_CSTRUCT */
     0x3,                     /* 3 */
     NdrFcShort(0x38),        /* 56 */
     NdrFcShort(0xfff0),      /* Offset= -16 (96) */
     0x08,                    /* FC_LONG */
     0x08,                    /* FC_LONG */
     0x4c,                    /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xff92), /* Offset= -110 (8) */
     0x4c,                    /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xffdc), /* Offset= -36 (86) */
     0x08,                    /* FC_LONG */
     0x5b,                    /* FC_END */
                              /* 126 (USN_VECTOR) */
     0x15,                    /* FC_STRUCT */
     0x7,                     /* 7 */
     NdrFcShort(0x18),        /* 24 */
     0x0b,                    /* FC_HYPER */
     0x0b,                    /* FC_HYPER */
     0x0b,                    /* FC_HYPER */
     0x5b,                    /* FC_END */
                              /* 134 (UPTODATE_CURSOR_V1) */
     0x15,                    /* FC_STRUCT */
     0x7,                     /* 7 */
     NdrFcShort(0x18),        /* 24 */
     0x4c,                    /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xff7c), /* Offset= -132 (8) */
     0x0b,                    /* FC_HYPER */
     0x5b,                    /* FC_END */
                              /* 144 (UPTODATE_CURSOR_V1[]) */
     0x1b,                    /* FC_CARRAY */
     0x7,                     /* 7 */
     NdrFcShort(0x18),        /* 24 */
     0x9,                     /* Corr desc: field cNumCursors, FC_ULONG */
     0x0,                     /* no operators */
     NdrFcShort(0xfff8),      /* offset = -8 */
     NdrFcShort(0x1), 0x4c,   /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xffea), /* Offset= -22 (134) */
     0x5c,                    /* FC_PAD */
     0x5b,                    /* FC_END */
                              /* 160 (UPTODATE_VECTOR_V1_EXT) */
     0x17,                    /* FC_CSTRUCT */
     0x7,                     /* 7 */
     NdrFcShort(0x10),        /* 16 */
     NdrFcShort(0xffec),      /* Offset= -20 (144) */
     0x08,                    /* FC_LONG */
     0x08,                    /* FC_LONG */
     0x08,                    /* FC_LONG */
     0x08,                    /* FC_LONG */
     0x5c,                    /* FC_PAD */
     0x5b,                    /* FC_END */
                              /* 172 (ATTRTYP[]) */
     0x1b,                    /* FC_CARRAY */
     0x3,                     /* 3 */
     NdrFcShort(0x4),         /* 4 */
     0x9,                     /* Corr desc: field cAttrs, FC_ULONG */
     0x0,                     /* no operators */
     NdrFcShort(0xfffc),      /* offset = -4 */
     NdrFcShort(0x1), 0x08,   /* FC_LONG */
     0x5b,                    /* FC_END */
                              /* 184 (PARTIAL_ATTR_VECTOR_V1_EXT) */
     0x17,                    /* FC_CSTRUCT */
     0x3,                     /* 3 */
     NdrFcShort(0xc),         /* 12 */
     NdrFcShort(0xfff0),      /* Offset= -16 (172) */
     0x08,                    /* FC_LONG */
     0x08,                    /* FC_LONG */
     0x08,                    /* FC_LONG */
     0x5b,                    /* FC_END */
                              /* 194 (unsigned char *) */
     0x1b,                    /* FC_CARRAY */
     0x0,                     /* 0 */
     NdrFcShort(0x1),         /* 1 */
     0x19,                    /* Corr desc: field pointer length, FC_ULONG */
     0x0,                     /* no operators */
     NdrFcShort(0x0),         /* offset = 0 */
     NdrFcShort(0x1), 0x02,   /* FC_CHAR */
     0x5b,                    /* FC_END */
                              /* 206 (OID_t) */
     0x1a,                    /* FC_BOGUS_STRUCT */
     0x3,                     /* 3 */
     NdrFcShort(0x10),        /* 16 */
     NdrFcShort(0x0), NdrFcShort(0x6), /* Offset= 6 (218) */
     0x08,                             /* FC_LONG */
     0x40,                             /* FC_STRUCTPAD4 */
     0x36,                             /* FC_POINTER */
     0x5b,                             /* FC_END */
                                       /* 218 */
     0x12, 0x0,                        /* FC_UP */
     NdrFcShort(0xffe6),               /* Offset= -26 (194) */
                                       /* 222 (PrefixTableEntry) */
     0x1a,                             /* FC_BOGUS_STRUCT */
     0x3,                              /* 3 */
     NdrFcShort(0x18),                 /* 24 */
     NdrFcShort(0x0), NdrFcShort(0x0), /* Offset= 0 (228) */
     0x08,                             /* FC_LONG */
     0x40,                             /* FC_STRUCTPAD4 */
     0x4c,                             /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xffe4),          /* Offset= -28 (206) */
     0x5c,                             /* FC_PAD */
     0x5b,                             /* FC_END */
                                       /* 238 (PrefixTableEntry *) */
     0x21,                             /* FC_BOGUS_ARRAY */
     0x3,                              /* 3 */
     NdrFcShort(0x0),                  /* 0 */
     0x19,            /* Corr desc: field pointer PrefixCount, FC_ULONG */
     0x0,             /* no operators */
     NdrFcShort(0x0), /* offset = 0 */
     NdrFcShort(0x1), NdrFcLong(0xffffffff), /* -1 */
     NdrFcShort(0x0), 0x4c,                  /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xffde),                /* Offset= -34 (222) */
     0x5c,                                   /* FC_PAD */
     0x5b,                                   /* FC_END */
                                             /* 260 (SCHEMA_PREFIX_TABLE) */
     0x1a,                                   /* FC_BOGUS_STRUCT */
     0x3,                                    /* 3 */
     NdrFcShort(0x10),                       /* 16 */
     NdrFcShort(0x0), NdrFcShort(0x6),       /* Offset= 6 (272) */
     0x08,                                   /* FC_LONG */
     0x40,                                   /* FC_STRUCTPAD4 */
     0x36,                                   /* FC_POINTER */
     0x5b,                                   /* FC_END */
                                             /* 272 */
     0x12, 0x0,                              /* FC_UP */
     NdrFcShort(0xffdc),                     /* Offset= -36 (238) */
                                             /* 276 (DRS_MSG_GETCHGREQ_V8) */
     0x1a,                                   /* FC_BOGUS_STRUCT */
     0x7,                                    /* 7 */
     NdrFcShort(0x80),                       /* 128 */
     NdrFcShort(0x0), NdrFcShort(0x1e),      /* Offset= 30 (312) */
     0x4c,                                   /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xfeea),                /* Offset= -278 (8) */
     0x4c,                                   /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xfee6),                /* Offset= -282 (8) */
     0x36,                                   /* FC_POINTER */
     0x4c,                                   /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xff57),                /* Offset= -169 (126) */
     0x36,                                   /* FC_POINTER */
     0x08,                                   /* FC_LONG */
     0x08,                                   /* FC_LONG */
     0x08,                                   /* FC_LONG */
     0x08,                                   /* FC_LONG */
     0x08,                                   /* FC_LONG */
     0x08,                                   /* FC_LONG */
     0x36,                                   /* FC_POINTER */
     0x36,                                   /* FC_POINTER */
     0x4c,                                   /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xffd0),                /* Offset= -48 (260) */
     0x5c,                                   /* FC_PAD */
     0x5b,                                   /* FC_END */
                                             /* 312 (DSNAME *) */
     0x12, 0x0,                              /* FC_UP */
     NdrFcShort(0xff32),                     /* Offset= -206 (108) */
     /* 316 (UPTODATE_VECTOR_V1_EXT *) */
     0x12, 0x0,          /* FC_UP */
     NdrFcShort(0xff62), /* Offset= -158 (160) */
                         /* 320 (PARTIAL_ATTR_VECTOR_V1_EXT *) */
     0x12, 0x0,          /* FC_UP */
     NdrFcShort(0xff76), /* Offset= -138 (184) */
                         /* 324 (PARTIAL_ATTR_VECTOR_V1_EXT *) */
     0x12, 0x0,          /* FC_UP */
     NdrFcShort(0xff72), /* Offset= -142 (184) */
                         /* 328 (DRS_MSG_GETCHGREQ) */
     0x2a,               /* FC_ENCAPSULATED_UNION */
     0x89,               /* Switch type= FC_ULONG */
     NdrFcShort(0x80),   /* 128 */
     NdrFcShort(0x1),    /* 1 */
     NdrFcLong(0x8),     /* 8 */
     NdrFcShort(0xffc2), /* Offset= -62 (276) */
     NdrFcShort(0xffff),
     /* 342 (DRS_MSG_GETCHGREQ *) */
     0x11, 0x0,               /* FC_RP */
     NdrFcShort(0xfff0),      /* Offset= -16 (328) */
                              /* 346 (ULONG *) */
     0x11, 0x8,               /* FC_RP [simple_pointer] */
     0x09,                    /* FC_ULONG */
     0x5c,                    /* FC_PAD */
                              /* 350 (UPTODATE_CURSOR_V2) */
     0x15,                    /* FC_STRUCT */
     0x7,                     /* 7 */
     NdrFcShort(0x20),        /* 32 */
     0x4c,                    /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xfea4), /* Offset= -348 (8) */
     0x0b,                    /* FC_HYPER */
     0x0b,                    /* FC_HYPER */
     0x5c,                    /* FC_PAD */
     0x5b,                    /* FC_END */
                              /* 362 (UPTODATE_CURSOR_V2[]) */
     0x1b,                    /* FC_CARRAY */
     0x7,                     /* 7 */
     NdrFcShort(0x20),        /* 32 */
     0x9,                     /* Corr desc: field cNumCursors, FC_ULONG */
     0x0,                     /* no operators */
     NdrFcShort(0xfff8),      /* offset = -8 */
     NdrFcShort(0x1), 0x4c,   /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xffe8), /* Offset= -24 (350) */
     0x5c,                    /* FC_PAD */
     0x5b,                    /* FC_END */
                              /* 378 (UPTODATE_VECTOR_V2_EXT) */
     0x17,                    /* FC_CSTRUCT */
     0x7,                     /* 7 */
     NdrFcShort(0x10),        /* 16 */
     NdrFcShort(0xffec),      /* Offset= -20 (362) */
     0x08,                    /* FC_LONG */
     0x08,                    /* FC_LONG */
     0x08,                    /* FC_LONG */
     0x08,                    /* FC_LONG */
     0x5c,                    /* FC_PAD */
     0x5b,                    /* FC_END */
                              /* 390 (unsigned char *) */
     0x1b,                    /* FC_CARRAY */
     0x0,                     /* 0 */
     NdrFcShort(0x1),         /* 1 */
     0x19,                    /* Corr desc: field pointer valLen, FC_ULONG */
     0x0,                     /* no operators */
     NdrFcShort(0x0),         /* offset = 0 */
     NdrFcShort(0x1), 0x02,   /* FC_CHAR */
     0x5b,                    /* FC_END */
                              /* 402 (ATTRVAL) */
     0x1a,                    /* FC_BOGUS_STRUCT */
     0x3,                     /* 3 */
     NdrFcShort(0x10),        /* 16 */
     NdrFcShort(0x0), NdrFcShort(0x6), /* Offset= 6 (414) */
     0x08,                             /* FC_LONG */
     0x40,                             /* FC_STRUCTPAD4 */
     0x36,                             /* FC_POINTER */
     0x5b,                             /* FC_END */
                                       /* 414 */
     0x12, 0x0,                        /* FC_UP */
     NdrFcShort(0xffe6),               /* Offset= -26 (390) */
                                       /* 418 (ATTRVAL *) */
     0x21,                             /* FC_BOGUS_ARRAY */
     0x3,                              /* 3 */
     NdrFcShort(0x0),                  /* 0 */
     0x19,            /* Corr desc: field pointer valCount, FC_ULONG */
     0x0,             /* no operators */
     NdrFcShort(0x0), /* offset = 0 */
     NdrFcShort(0x1), NdrFcLong(0xffffffff), /* -1 */
     NdrFcShort(0x0), 0x4c,                  /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xffde),                /* Offset= -34 (402) */
     0x5c,                                   /* FC_PAD */
     0x5b,                                   /* FC_END */
                                             /* 440 (ATTRVALBLOCK) */
     0x1a,                                   /* FC_BOGUS_STRUCT */
     0x3,                                    /* 3 */
     NdrFcShort(0x10),                       /* 16 */
     NdrFcShort(0x0), NdrFcShort(0x6),       /* Offset= 6 (452) */
     0x08,                                   /* FC_LONG */
     0x40,                                   /* FC_STRUCTPAD4 */
     0x36,                                   /* FC_POINTER */
     0x5b,                                   /* FC_END */
                                             /* 452 */
     0x12, 0x0,                              /* FC_UP */
     NdrFcShort(0xffdc),                     /* Offset= -36 (418) */
                                             /* 456 (ATTR) */
     0x1a,                                   /* FC_BOGUS_STRUCT */
     0x3,                                    /* 3 */
     NdrFcShort(0x18),                       /* 24 */
     NdrFcShort(0x0), NdrFcShort(0x0),       /* Offset= 0 (462) */
     0x08,                                   /* FC_LONG */
     0x40,                                   /* FC_STRUCTPAD4 */
     0x4c,                                   /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xffe4),                /* Offset= -28 (440) */
     0x5c,                                   /* FC_PAD */
     0x5b,                                   /* FC_END */
                                             /* 472 (ATTR *) */
     0x21,                                   /* FC_BOGUS_ARRAY */
     0x3,                                    /* 3 */
     NdrFcShort(0x0),                        /* 0 */
     0x19,            /* Corr desc: field pointer attrCount, FC_ULONG */
     0x0,             /* no operators */
     NdrFcShort(0x0), /* offset = 0 */
     NdrFcShort(0x1), NdrFcLong(0xffffffff), /* -1 */
     NdrFcShort(0x0), 0x4c,                  /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xffde),                /* Offset= -34 (456) */
     0x5c,                                   /* FC_PAD */
     0x5b,                                   /* FC_END */
                                             /* 494 (ATTRBLOCK) */
     0x1a,                                   /* FC_BOGUS_STRUCT */
     0x3,                                    /* 3 */
     NdrFcShort(0x10),                       /* 16 */
     NdrFcShort(0x0), NdrFcShort(0x6),       /* Offset= 6 (506) */
     0x08,                                   /* FC_LONG */
     0x40,                                   /* FC_STRUCTPAD4 */
     0x36,                                   /* FC_POINTER */
     0x5b,                                   /* FC_END */
                                             /* 506 */
     0x12, 0x0,                              /* FC_UP */
     NdrFcShort(0xffdc),                     /* Offset= -36 (472) */
                                             /* 510 (ENTINF) */
     0x1a,                                   /* FC_BOGUS_STRUCT */
     0x3,                                    /* 3 */
     NdrFcShort(0x20),                       /* 32 */
     NdrFcShort(0x0), NdrFcShort(0xa),       /* Offset= 10 (526) */
     0x36,                                   /* FC_POINTER */
     0x08,                                   /* FC_LONG */
     0x40,                                   /* FC_STRUCTPAD4 */
     0x4c,                                   /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xffe3),                /* Offset= -29 (494) */
     0x5b,                                   /* FC_END */
                                             /* 526 (DSNAME *) */
     0x12, 0x0,                              /* FC_UP */
     NdrFcShort(0xfe5c),                     /* Offset= -420 (108) */
                                             /* 530 (PROPERTY_META_DATA_EXT) */
     0x15,                                   /* FC_STRUCT */
     0x7,                                    /* 7 */
     NdrFcShort(0x28),                       /* 40 */
     0x08,                                   /* FC_LONG */
     0x40,                                   /* FC_STRUCTPAD4 */
     0x0b,                                   /* FC_HYPER */
     0x4c,                                   /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xfded),                /* Offset= -531 (8) */
     0x0b,                                   /* FC_HYPER */
     0x5c,                                   /* FC_PAD */
     0x5b,                                   /* FC_END */
     /* 544 (PROPERTY_META_DATA_EXT[]) */
     0x1b,                    /* FC_CARRAY */
     0x7,                     /* 7 */
     NdrFcShort(0x28),        /* 40 */
     0x9,                     /* Corr desc: field cNumProps, FC_ULONG */
     0x0,                     /* no operators */
     NdrFcShort(0xfff8),      /* offset = -8 */
     NdrFcShort(0x1), 0x4c,   /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xffe6), /* Offset= -26 (530) */
     0x5c,                    /* FC_PAD */
     0x5b,                    /* FC_END */
                              /* 560 (PROPERTY_META_DATA_EXT_VECTOR) */
     0x17,                    /* FC_CSTRUCT */
     0x7,                     /* 7 */
     NdrFcShort(0x8),         /* 8 */
     NdrFcShort(0xffec),      /* Offset= -20 (544) */
     0x08,                    /* FC_LONG */
     0x40,                    /* FC_STRUCTPAD4 */
     0x5c,                    /* FC_PAD */
     0x5b,                    /* FC_END */
                              /* 570 (struct _REPLENTINFLIST) */
     0x1a,                    /* FC_BOGUS_STRUCT */
     0x3,                     /* 3 */
     NdrFcShort(0x40),        /* 64 */
     NdrFcShort(0x0), NdrFcShort(0xc), /* Offset= 12 (588) */
     0x36,                             /* FC_POINTER */
     0x4c,                             /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xffb9),          /* Offset= -71 (510) */
     0x08,                             /* FC_LONG */
     0x40,                             /* FC_STRUCTPAD4 */
     0x36,                             /* FC_POINTER */
     0x36,                             /* FC_POINTER */
     0x5b,                             /* FC_END */
                                       /* 588 (struct _REPLENTINFLIST *) */
     0x12, 0x0,                        /* FC_UP */
     NdrFcShort(0xffec),               /* Offset= -20 (570) */
                                       /* 592 (GUID *) */
     0x12, 0x0,                        /* FC_UP */
     NdrFcShort(0xfdb6),               /* Offset= -586 (8) */
     /* 596 (PROPERTY_META_DATA_EXT_VECTOR *) */
     0x12, 0x0,                        /* FC_UP */
     NdrFcShort(0xffda),               /* Offset= -38 (560) */
                                       /* 600 (REPLENTINFLIST) */
     0x1a,                             /* FC_BOGUS_STRUCT */
     0x3,                              /* 3 */
     NdrFcShort(0x40),                 /* 64 */
     NdrFcShort(0x0), NdrFcShort(0xc), /* Offset= 12 (618) */
     0x36,                             /* FC_POINTER */
     0x4c,                             /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xff9b),          /* Offset= -101 (510) */
     0x08,                             /* FC_LONG */
     0x40,                             /* FC_STRUCTPAD4 */
     0x36,                             /* FC_POINTER */
     0x36,                             /* FC_POINTER */
     0x5b,                             /* FC_END */
                                       /* 618 (struct _REPLENTINFLIST *) */
     0x12, 0x0,                        /* FC_UP */
     NdrFcShort(0xffce),               /* Offset= -50 (570) */
                                       /* 622 (GUID *) */
     0x12, 0x0,                        /* FC_UP */
     NdrFcShort(0xfd98),               /* Offset= -616 (8) */
     /* 626 (PROPERTY_META_DATA_EXT_VECTOR *) */
     0x12, 0x0,                         /* FC_UP */
     NdrFcShort(0xffbc),                /* Offset= -68 (560) */
                                        /* 630 (VALUE_META_DATA_EXT_V1) */
     0x15,                              /* FC_STRUCT */
     0x7,                               /* 7 */
     NdrFcShort(0x30),                  /* 48 */
     0x0b,                              /* FC_HYPER */
     0x4c,                              /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xff95),           /* Offset= -107 (530) */
     0x5b,                              /* FC_END */
                                        /* 640 (REPLVALINF_V1) */
     0x1a,                              /* FC_BOGUS_STRUCT */
     0x7,                               /* 7 */
     NdrFcShort(0x58),                  /* 88 */
     NdrFcShort(0x0), NdrFcShort(0x10), /* Offset= 16 (662) */
     0x36,                              /* FC_POINTER */
     0x08,                              /* FC_LONG */
     0x40,                              /* FC_STRUCTPAD4 */
     0x4c,                              /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xff05),           /* Offset= -251 (402) */
     0x08,                              /* FC_LONG */
     0x40,                              /* FC_STRUCTPAD4 */
     0x4c,                              /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xffe3),           /* Offset= -29 (630) */
     0x5b,                              /* FC_END */
                                        /* 662 (DSNAME *) */
     0x12, 0x0,                         /* FC_UP */
     NdrFcShort(0xfdd4),                /* Offset= -556 (108) */
                                        /* 666 (REPLVALINF_V1 *) */
     0x21,                              /* FC_BOGUS_ARRAY */
     0x7,                               /* 7 */
     NdrFcShort(0x0),                   /* 0 */
     0x19,             /* Corr desc: field pointer cNumValues, FC_ULONG */
     0x0,              /* no operators */
     NdrFcShort(0x94), /* offset = 148 */
     NdrFcShort(0x0), NdrFcLong(0xffffffff), /* -1 */
     NdrFcShort(0x0), 0x4c,                  /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xffd4),                /* Offset= -44 (640) */
     0x5c,                                   /* FC_PAD */
     0x5b,                                   /* FC_END */
                                             /* 688 (DRS_MSG_GETCHGREPLY_V6) */
     0x1a,                                   /* FC_BOGUS_STRUCT */
     0x7,                                    /* 7 */
     NdrFcShort(0xa8),                       /* 168 */
     NdrFcShort(0x0), NdrFcShort(0x26),      /* Offset= 38 (732) */
     0x4c,                                   /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xfd4e),                /* Offset= -690 (8) */
     0x4c,                                   /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xfd4a),                /* Offset= -694 (8) */
     0x36,                                   /* FC_POINTER */
     0x4c,                                   /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xfdbb),                /* Offset= -581 (126) */
     0x4c,                                   /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xfdb7),                /* Offset= -585 (126) */
     0x36,                                   /* FC_POINTER */
     0x4c,                                   /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xfe38),                /* Offset= -456 (260) */
     0x08,                                   /* FC_LONG */
     0x08,                                   /* FC_LONG */
     0x08,                                   /* FC_LONG */
     0x40,                                   /* FC_STRUCTPAD4 */
     0x36,                                   /* FC_POINTER */
     0x08,                                   /* FC_LONG */
     0x08,                                   /* FC_LONG */
     0x08,                                   /* FC_LONG */
     0x08,                                   /* FC_LONG */
     0x36,                                   /* FC_POINTER */
     0x08,                                   /* FC_LONG */
     0x40,                                   /* FC_STRUCTPAD4 */
     0x5c,                                   /* FC_PAD */
     0x5b,                                   /* FC_END */
                                             /* 732 (DSNAME *) */
     0x12, 0x0,                              /* FC_UP */
     NdrFcShort(0xfd8e),                     /* Offset= -626 (108) */
     /* 736 (UPTODATE_VECTOR_V2_EXT *) */
     0x12, 0x0,          /* FC_UP */
     NdrFcShort(0xfe98), /* Offset= -360 (378) */
                         /* 740 (REPLENTINFLIST *) */
     0x12, 0x0,          /* FC_UP */
     NdrFcShort(0xff72), /* Offset= -142 (600) */
                         /* 744 */
     0x12, 0x0,          /* FC_UP */
     NdrFcShort(0xffb0), /* Offset= -80 (666) */
                         /* 748 (DRS_MSG_GETCHGREPLY) */
     0x2a,               /* FC_ENCAPSULATED_UNION */
     0x89,               /* Switch type= FC_ULONG */
     NdrFcShort(0xa8),   /* 168 */
     NdrFcShort(0x1),    /* 1 */
     NdrFcLong(0x6),     /* 6 */
     NdrFcShort(0xffba), /* Offset= -70 (688) */
     NdrFcShort(0xffff),
     /* 762 (DRS_MSG_GETCHGREPLY *) */
     0x11, 0x0,          /* FC_RP */
     NdrFcShort(0xfff0), /* Offset= -16 (748) */
                         /* 766 (DRS_HANDLE) */
     0x30,               /* FC_BIND_CONTEXT */
     0x41,               /* Context flags: can't be null, in, */
     0x0,                /* rundown routine */
     0,                  /* FIXME: param num */
                         /* 770 (DRS_HANDLE) */
     0x30,               /* FC_BIND_CONTEXT */
     0x41,               /* Context flags: can't be null, in, */
     0x0,                /* rundown routine */
     0,                  /* FIXME: param num */
                         /* 774 (DRS_HANDLE) */
     0x30,               /* FC_BIND_CONTEXT */
     0x41,               /* Context flags: can't be null, in, */
     0x0,                /* rundown routine */
     0,                  /* FIXME: param num */
                         /* 778 (DRS_HANDLE) */
     0x30,               /* FC_BIND_CONTEXT */
     0x41,               /* Context flags: can't be null, in, */
     0x0,                /* rundown routine */
     0,                  /* FIXME: param num */
                         /* 782 (DRS_HANDLE) */
     0x30,               /* FC_BIND_CONTEXT */
     0x41,               /* Context flags: can't be null, in, */
     0x0,                /* rundown routine */
     0,                  /* FIXME: param num */
                         /* 786 (DRS_HANDLE) */
     0x30,               /* FC_BIND_CONTEXT */
     0x41,               /* Context flags: can't be null, in, */
     0x0,                /* rundown routine */
     0,                  /* FIXME: param num */
                         /* 790 (DRS_HANDLE) */
     0x30,               /* FC_BIND_CONTEXT */
     0x41,               /* Context flags: can't be null, in, */
     0x0,                /* rundown routine */
     0,                  /* FIXME: param num */
                         /* 794 (DRS_HANDLE) */
     0x30,               /* FC_BIND_CONTEXT */
     0x41,               /* Context flags: can't be null, in, */
     0x0,                /* rundown routine */
     0,                  /* FIXME: param num */
                         /* 798 (DRS_HANDLE) */
     0x30,               /* FC_BIND_CONTEXT */
     0x41,               /* Context flags: can't be null, in, */
     0x0,                /* rundown routine */
     0,                  /* FIXME: param num */
                         /* 802 (wchar_t **) */
     0x12, 0x0,          /* FC_UP */
     NdrFcShort(0x2),
     /* 806 (wchar_t **) */
     0x21,             /* FC_BOGUS_ARRAY */
     0x3,              /* 3 */
     NdrFcShort(0x0),  /* 0 */
     0x19,             /* Corr desc: field pointer cNames, FC_ULONG */
     0x0,              /* no operators */
     NdrFcShort(0x14), /* offset = 20 */
     NdrFcShort(0x0), NdrFcLong(0xffffffff), /* -1 */
     NdrFcShort(0x0),
     /* 822 (wchar_t *) */
     0x12, 0x8,                        /* FC_UP [simple_pointer] */
                                       /* 824 */
     0x25,                             /* FC_C_WSTRING */
     0x5c,                             /* FC_PAD */
     0x5c,                             /* FC_PAD */
     0x5b,                             /* FC_END */
                                       /* 828 (DRS_MSG_CRACKREQ_V1) */
     0x1a,                             /* FC_BOGUS_STRUCT */
     0x3,                              /* 3 */
     NdrFcShort(0x20),                 /* 32 */
     NdrFcShort(0x0), NdrFcShort(0xa), /* Offset= 10 (844) */
     0x08,                             /* FC_LONG */
     0x08,                             /* FC_LONG */
     0x08,                             /* FC_LONG */
     0x08,                             /* FC_LONG */
     0x08,                             /* FC_LONG */
     0x08,                             /* FC_LONG */
     0x36,                             /* FC_POINTER */
     0x5b,                             /* FC_END */
                                       /* 844 */
     0x12, 0x0,                        /* FC_UP */
     NdrFcShort(0xffdc),               /* Offset= -36 (810) */
                                       /* 848 (DRS_MSG_CRACKREQ) */
     0x2a,                             /* FC_ENCAPSULATED_UNION */
     0x89,                             /* Switch type= FC_ULONG */
     NdrFcShort(0x20),                 /* 32 */
     NdrFcShort(0x1),                  /* 1 */
     NdrFcLong(0x1),                   /* 1 */
     NdrFcShort(0xffe2),               /* Offset= -30 (828) */
     NdrFcShort(0xffff),
     /* 862 (DRS_MSG_CRACKREQ *) */
     0x11, 0x0,                        /* FC_RP */
     NdrFcShort(0xfff0),               /* Offset= -16 (848) */
                                       /* 866 (ULONG *) */
     0x11, 0x8,                        /* FC_RP [simple_pointer] */
     0x09,                             /* FC_ULONG */
     0x5c,                             /* FC_PAD */
                                       /* 870 (wchar_t *) */
     0x12, 0x8,                        /* FC_UP [simple_pointer] */
                                       /* 872 */
     0x25,                             /* FC_C_WSTRING */
     0x5c,                             /* FC_PAD */
                                       /* 874 (wchar_t *) */
     0x12, 0x8,                        /* FC_UP [simple_pointer] */
                                       /* 876 */
     0x25,                             /* FC_C_WSTRING */
     0x5c,                             /* FC_PAD */
                                       /* 878 (DS_NAME_RESULT_ITEMW) */
     0x1a,                             /* FC_BOGUS_STRUCT */
     0x3,                              /* 3 */
     NdrFcShort(0x18),                 /* 24 */
     NdrFcShort(0x0), NdrFcShort(0x8), /* Offset= 8 (892) */
     0x08,                             /* FC_LONG */
     0x40,                             /* FC_STRUCTPAD4 */
     0x36,                             /* FC_POINTER */
     0x36,                             /* FC_POINTER */
     0x5c,                             /* FC_PAD */
     0x5b,                             /* FC_END */
                                       /* 892 (wchar_t *) */
     0x12, 0x8,                        /* FC_UP [simple_pointer] */
                                       /* 894 */
     0x25,                             /* FC_C_WSTRING */
     0x5c,                             /* FC_PAD */
                                       /* 896 (wchar_t *) */
     0x12, 0x8,                        /* FC_UP [simple_pointer] */
                                       /* 898 */
     0x25,                             /* FC_C_WSTRING */
     0x5c,                             /* FC_PAD */
                                       /* 900 (DS_NAME_RESULT_ITEMW *) */
     0x21,                             /* FC_BOGUS_ARRAY */
     0x3,                              /* 3 */
     NdrFcShort(0x0),                  /* 0 */
     0x19,            /* Corr desc: field pointer cItems, FC_ULONG */
     0x0,             /* no operators */
     NdrFcShort(0x0), /* offset = 0 */
     NdrFcShort(0x1), NdrFcLong(0xffffffff), /* -1 */
     NdrFcShort(0x0), 0x4c,                  /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xffd8),                /* Offset= -40 (878) */
     0x5c,                                   /* FC_PAD */
     0x5b,                                   /* FC_END */
                                             /* 922 (DS_NAME_RESULTW) */
     0x1a,                                   /* FC_BOGUS_STRUCT */
     0x3,                                    /* 3 */
     NdrFcShort(0x10),                       /* 16 */
     NdrFcShort(0x0), NdrFcShort(0x6),       /* Offset= 6 (934) */
     0x08,                                   /* FC_LONG */
     0x40,                                   /* FC_STRUCTPAD4 */
     0x36,                                   /* FC_POINTER */
     0x5b,                                   /* FC_END */
                                             /* 934 */
     0x12, 0x0,                              /* FC_UP */
     NdrFcShort(0xffdc),                     /* Offset= -36 (900) */
                                             /* 938 (DRS_MSG_CRACKREPLY_V1) */
     0x1a,                                   /* FC_BOGUS_STRUCT */
     0x3,                                    /* 3 */
     NdrFcShort(0x8),                        /* 8 */
     NdrFcShort(0x0), NdrFcShort(0x4),       /* Offset= 4 (948) */
     0x36,                                   /* FC_POINTER */
     0x5b,                                   /* FC_END */
                                             /* 948 (DS_NAME_RESULTW *) */
     0x12, 0x0,                              /* FC_UP */
     NdrFcShort(0xffe4),                     /* Offset= -28 (922) */
                                             /* 952 (DRS_MSG_CRACKREPLY) */
     0x2a,                                   /* FC_ENCAPSULATED_UNION */
     0x89,                                   /* Switch type= FC_ULONG */
     NdrFcShort(0x8),                        /* 8 */
     NdrFcShort(0x1),                        /* 1 */
     NdrFcLong(0x1),                         /* 1 */
     NdrFcShort(0xffe8),                     /* Offset= -24 (938) */
     NdrFcShort(0xffff),
     /* 966 (DRS_MSG_CRACKREPLY *) */
     0x11, 0x0,                        /* FC_RP */
     NdrFcShort(0xfff0),               /* Offset= -16 (952) */
                                       /* 970 (DRS_HANDLE) */
     0x30,                             /* FC_BIND_CONTEXT */
     0x41,                             /* Context flags: can't be null, in, */
     0x0,                              /* rundown routine */
     0,                                /* FIXME: param num */
                                       /* 974 (DRS_HANDLE) */
     0x30,                             /* FC_BIND_CONTEXT */
     0x41,                             /* Context flags: can't be null, in, */
     0x0,                              /* rundown routine */
     0,                                /* FIXME: param num */
                                       /* 978 (DRS_HANDLE) */
     0x30,                             /* FC_BIND_CONTEXT */
     0x41,                             /* Context flags: can't be null, in, */
     0x0,                              /* rundown routine */
     0,                                /* FIXME: param num */
                                       /* 982 (DRS_HANDLE) */
     0x30,                             /* FC_BIND_CONTEXT */
     0x41,                             /* Context flags: can't be null, in, */
     0x0,                              /* rundown routine */
     0,                                /* FIXME: param num */
                                       /* 986 (wchar_t *) */
     0x12, 0x8,                        /* FC_UP [simple_pointer] */
                                       /* 988 */
     0x25,                             /* FC_C_WSTRING */
     0x5c,                             /* FC_PAD */
                                       /* 990 (DRS_MSG_DCINFOREQ_V1) */
     0x1a,                             /* FC_BOGUS_STRUCT */
     0x3,                              /* 3 */
     NdrFcShort(0x10),                 /* 16 */
     NdrFcShort(0x0), NdrFcShort(0x6), /* Offset= 6 (1002) */
     0x36,                             /* FC_POINTER */
     0x08,                             /* FC_LONG */
     0x40,                             /* FC_STRUCTPAD4 */
     0x5b,                             /* FC_END */
                                       /* 1002 (wchar_t *) */
     0x12, 0x8,                        /* FC_UP [simple_pointer] */
                                       /* 1004 */
     0x25,                             /* FC_C_WSTRING */
     0x5c,                             /* FC_PAD */
                                       /* 1006 (DRS_MSG_DCINFOREQ) */
     0x2a,                             /* FC_ENCAPSULATED_UNION */
     0x89,                             /* Switch type= FC_ULONG */
     NdrFcShort(0x10),                 /* 16 */
     NdrFcShort(0x1),                  /* 1 */
     NdrFcLong(0x1),                   /* 1 */
     NdrFcShort(0xffe6),               /* Offset= -26 (990) */
     NdrFcShort(0xffff),
     /* 1020 (DRS_MSG_DCINFOREQ *) */
     0x11, 0x0,          /* FC_RP */
     NdrFcShort(0xfff0), /* Offset= -16 (1006) */
                         /* 1024 (ULONG *) */
     0x11, 0x8,          /* FC_RP [simple_pointer] */
     0x09,               /* FC_ULONG */
     0x5c,               /* FC_PAD */
                         /* 1028 (wchar_t *) */
     0x12, 0x8,          /* FC_UP [simple_pointer] */
                         /* 1030 */
     0x25,               /* FC_C_WSTRING */
     0x5c,               /* FC_PAD */
                         /* 1032 (wchar_t *) */
     0x12, 0x8,          /* FC_UP [simple_pointer] */
                         /* 1034 */
     0x25,               /* FC_C_WSTRING */
     0x5c,               /* FC_PAD */
                         /* 1036 (wchar_t *) */
     0x12, 0x8,          /* FC_UP [simple_pointer] */
                         /* 1038 */
     0x25,               /* FC_C_WSTRING */
     0x5c,               /* FC_PAD */
                         /* 1040 (wchar_t *) */
     0x12, 0x8,          /* FC_UP [simple_pointer] */
                         /* 1042 */
     0x25,               /* FC_C_WSTRING */
     0x5c,               /* FC_PAD */
                         /* 1044 (wchar_t *) */
     0x12, 0x8,          /* FC_UP [simple_pointer] */
                         /* 1046 */
     0x25,               /* FC_C_WSTRING */
     0x5c,               /* FC_PAD */
                         /* 1048 (wchar_t *) */
     0x12, 0x8,          /* FC_UP [simple_pointer] */
                         /* 1050 */
     0x25,               /* FC_C_WSTRING */
     0x5c,               /* FC_PAD */
                         /* 1052 (wchar_t *) */
     0x12, 0x8,          /* FC_UP [simple_pointer] */
                         /* 1054 */
     0x25,               /* FC_C_WSTRING */
     0x5c,               /* FC_PAD */
                         /* 1056 (DS_DOMAIN_CONTROLLER_INFO_2W) */
     0x1a,               /* FC_BOGUS_STRUCT */
     0x3,                /* 3 */
     NdrFcShort(0x88),   /* 136 */
     NdrFcShort(0x0), NdrFcShort(0x1e), /* Offset= 30 (1092) */
     0x36,                              /* FC_POINTER */
     0x36,                              /* FC_POINTER */
     0x36,                              /* FC_POINTER */
     0x36,                              /* FC_POINTER */
     0x36,                              /* FC_POINTER */
     0x36,                              /* FC_POINTER */
     0x36,                              /* FC_POINTER */
     0x08,                              /* FC_LONG */
     0x08,                              /* FC_LONG */
     0x08,                              /* FC_LONG */
     0x4c,                              /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xfbd4),           /* Offset= -1068 (8) */
     0x4c,                              /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xfbd0),           /* Offset= -1072 (8) */
     0x4c,                              /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xfbcc),           /* Offset= -1076 (8) */
     0x4c,                              /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xfbc8),           /* Offset= -1080 (8) */
     0x40,                              /* FC_STRUCTPAD4 */
     0x5b,                              /* FC_END */
                                        /* 1092 (wchar_t *) */
     0x12, 0x8,                         /* FC_UP [simple_pointer] */
                                        /* 1094 */
     0x25,                              /* FC_C_WSTRING */
     0x5c,                              /* FC_PAD */
                                        /* 1096 (wchar_t *) */
     0x12, 0x8,                         /* FC_UP [simple_pointer] */
                                        /* 1098 */
     0x25,                              /* FC_C_WSTRING */
     0x5c,                              /* FC_PAD */
                                        /* 1100 (wchar_t *) */
     0x12, 0x8,                         /* FC_UP [simple_pointer] */
                                        /* 1102 */
     0x25,                              /* FC_C_WSTRING */
     0x5c,                              /* FC_PAD */
                                        /* 1104 (wchar_t *) */
     0x12, 0x8,                         /* FC_UP [simple_pointer] */
                                        /* 1106 */
     0x25,                              /* FC_C_WSTRING */
     0x5c,                              /* FC_PAD */
                                        /* 1108 (wchar_t *) */
     0x12, 0x8,                         /* FC_UP [simple_pointer] */
                                        /* 1110 */
     0x25,                              /* FC_C_WSTRING */
     0x5c,                              /* FC_PAD */
                                        /* 1112 (wchar_t *) */
     0x12, 0x8,                         /* FC_UP [simple_pointer] */
                                        /* 1114 */
     0x25,                              /* FC_C_WSTRING */
     0x5c,                              /* FC_PAD */
                                        /* 1116 (wchar_t *) */
     0x12, 0x8,                         /* FC_UP [simple_pointer] */
                                        /* 1118 */
     0x25,                              /* FC_C_WSTRING */
     0x5c,                              /* FC_PAD */
     /* 1120 (DS_DOMAIN_CONTROLLER_INFO_2W *) */
     0x21,            /* FC_BOGUS_ARRAY */
     0x3,             /* 3 */
     NdrFcShort(0x0), /* 0 */
     0x19,            /* Corr desc: field pointer cItems, FC_ULONG */
     0x0,             /* no operators */
     NdrFcShort(0x0), /* offset = 0 */
     NdrFcShort(0x1), NdrFcLong(0xffffffff), /* -1 */
     NdrFcShort(0x0), 0x4c,                  /* FC_EMBEDDED_COMPLEX */
     0x0, NdrFcShort(0xffae),                /* Offset= -82 (1056) */
     0x5c,                                   /* FC_PAD */
     0x5b,                                   /* FC_END */
                                             /* 1142 (DRS_MSG_DCINFOREPLY_V2) */
     0x1a,                                   /* FC_BOGUS_STRUCT */
     0x3,                                    /* 3 */
     NdrFcShort(0x10),                       /* 16 */
     NdrFcShort(0x0), NdrFcShort(0x6),       /* Offset= 6 (1154) */
     0x08,                                   /* FC_LONG */
     0x40,                                   /* FC_STRUCTPAD4 */
     0x36,                                   /* FC_POINTER */
     0x5b,                                   /* FC_END */
                                             /* 1154 */
     0x12, 0x0,                              /* FC_UP */
     NdrFcShort(0xffdc),                     /* Offset= -36 (1120) */
                                             /* 1158 (DRS_MSG_DCINFOREPLY) */
     0x2a,                                   /* FC_ENCAPSULATED_UNION */
     0x89,                                   /* Switch type= FC_ULONG */
     NdrFcShort(0x10),                       /* 16 */
     NdrFcShort(0x1),                        /* 1 */
     NdrFcLong(0x2),                         /* 2 */
     NdrFcShort(0xffe6),                     /* Offset= -26 (1142) */
     NdrFcShort(0xffff),
     /* 1172 (DRS_MSG_DCINFOREPLY *) */
     0x11, 0x0,          /* FC_RP */
     NdrFcShort(0xfff0), /* Offset= -16 (1158) */
     0x0}};
