/*** Autogenerated by WIDL 11.7 from drsuapi_min.idl - Do not edit ***/
#include "common/common.h"
#include <windows.h>

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <ole2.h>
#include <windows.h>
#endif

#ifndef __drsuapi_h__
#define __drsuapi_h__

/* Forward declarations */

/* Headers for imported files */

#include <oaidl.h>

#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * drsuapi interface (v4.0)
 */
#ifndef __drsuapi_INTERFACE_DEFINED__
#define __drsuapi_INTERFACE_DEFINED__

extern RPC_IF_HANDLE drsuapi_v4_0_c_ifspec;
extern RPC_IF_HANDLE drsuapi_v4_0_s_ifspec;
typedef void *DRS_HANDLE;
typedef INT64 DSTIME;
typedef INT64 USN;
typedef ULONG ATTRTYP;
typedef struct _NT4SID {
  unsigned char Data[28];
} NT4SID;
typedef struct _DSNAME {
  ULONG structLen;
  ULONG SidLen;
  GUID Guid;
  NT4SID Sid;
  ULONG NameLen;
  wchar_t StringName[1];
} DSNAME;
typedef struct _USN_VECTOR {
  USN usnHighObjUpdate;
  USN usnReserved;
  USN usnHighPropUpdate;
} USN_VECTOR;
typedef struct _UPTODATE_CURSOR_V1 {
  GUID uuidDsa;
  USN usnHighPropUpdate;
} UPTODATE_CURSOR_V1;
typedef struct _UPTODATE_VECTOR_V1_EXT {
  ULONG dwVersion;
  ULONG dwReserved1;
  ULONG cNumCursors;
  ULONG dwReserved2;
  UPTODATE_CURSOR_V1 rgCursors[1];
} UPTODATE_VECTOR_V1_EXT;
typedef struct _UPTODATE_CURSOR_V2 {
  GUID uuidDsa;
  USN usnHighPropUpdate;
  DSTIME timeLastSyncSuccess;
} UPTODATE_CURSOR_V2;
typedef struct _UPTODATE_VECTOR_V2_EXT {
  ULONG dwVersion;
  ULONG dwReserved1;
  ULONG cNumCursors;
  ULONG dwReserved2;
  UPTODATE_CURSOR_V2 rgCursors[1];
} UPTODATE_VECTOR_V2_EXT;
typedef struct _OID_t {
  ULONG length;
  unsigned char *elements;
} OID_t;
typedef struct _PrefixTableEntry {
  ULONG ndx;
  OID_t prefix;
} PrefixTableEntry;
typedef struct _SCHEMA_PREFIX_TABLE {
  ULONG PrefixCount;
  PrefixTableEntry *pPrefixEntry;
} SCHEMA_PREFIX_TABLE;
typedef struct _PARTIAL_ATTR_VECTOR_V1_EXT {
  ULONG dwVersion;
  ULONG dwReserved1;
  ULONG cAttrs;
  ATTRTYP rgPartialAttr[1];
} PARTIAL_ATTR_VECTOR_V1_EXT;
typedef struct _PROPERTY_META_DATA_EXT {
  ULONG dwVersion;
  DSTIME timeChanged;
  GUID uuidDsaOriginating;
  USN usnOriginating;
} PROPERTY_META_DATA_EXT;
typedef struct _PROPERTY_META_DATA_EXT_VECTOR {
  ULONG cNumProps;
  PROPERTY_META_DATA_EXT rgMetaData[1];
} PROPERTY_META_DATA_EXT_VECTOR;
typedef struct _ATTRVAL {
  ULONG valLen;
  unsigned char *pVal;
} ATTRVAL;
typedef struct _ATTRVALBLOCK {
  ULONG valCount;
  ATTRVAL *pAVal;
} ATTRVALBLOCK;
typedef struct _ATTR {
  ATTRTYP attrTyp;
  ATTRVALBLOCK AttrVal;
} ATTR;
typedef struct _ATTRBLOCK {
  ULONG attrCount;
  ATTR *pAttr;
} ATTRBLOCK;
typedef struct _ENTINF {
  DSNAME *pName;
  ULONG ulFlags;
  ATTRBLOCK AttrBlock;
} ENTINF;
typedef struct _REPLENTINFLIST {
  struct _REPLENTINFLIST *pNextEntInf;
  ENTINF Entinf;
  LONG fIsNCPrefix;
  GUID *pParentGuid;
  PROPERTY_META_DATA_EXT_VECTOR *pMetaDataExt;
} REPLENTINFLIST;
typedef struct _VALUE_META_DATA_EXT_V1 {
  DSTIME timeCreated;
  PROPERTY_META_DATA_EXT MetaData;
} VALUE_META_DATA_EXT_V1;
typedef struct _REPLVALINF_V1 {
  DSNAME *pObject;
  ATTRTYP attrTyp;
  ATTRVAL Aval;
  LONG fIsPresent;
  VALUE_META_DATA_EXT_V1 MetaData;
} REPLVALINF_V1;
typedef struct __WIDL_drsuapi_min_generated_name_0000000E {
  ULONG cb;
  unsigned char rgb[1];
} DRS_EXTENSIONS;
typedef struct _DRS_MSG_GETCHGREQ_V8 {
  GUID uuidDsaObjDest;
  GUID uuidInvocIdSrc;
  DSNAME *pNC;
  USN_VECTOR usnvecFrom;
  UPTODATE_VECTOR_V1_EXT *pUpToDateVecDest;
  ULONG ulFlags;
  ULONG cMaxObjects;
  ULONG cMaxBytes;
  ULONG ulExtendedOp;
  ULONG liFsmoInfo_LowPart;
  ULONG liFsmoInfo_HighPart;
  PARTIAL_ATTR_VECTOR_V1_EXT *pPartialAttrSet;
  PARTIAL_ATTR_VECTOR_V1_EXT *pPartialAttrSetEx;
  SCHEMA_PREFIX_TABLE PrefixTableDest;
} DRS_MSG_GETCHGREQ_V8;
typedef struct _DRS_MSG_GETCHGREQ {
  ULONG dwInVersion;
  union __WIDL_drsuapi_min_generated_name_0000000F {
    DRS_MSG_GETCHGREQ_V8 V8;
  } tagged_union;
} DRS_MSG_GETCHGREQ;
typedef struct _DRS_MSG_GETCHGREPLY_V6 {
  GUID uuidDsaObjSrc;
  GUID uuidInvocIdSrc;
  DSNAME *pNC;
  USN_VECTOR usnvecFrom;
  USN_VECTOR usnvecTo;
  UPTODATE_VECTOR_V2_EXT *pUpToDateVecSrc;
  SCHEMA_PREFIX_TABLE PrefixTableSrc;
  ULONG ulExtendedRet;
  ULONG cNumObjects;
  ULONG cNumBytes;
  REPLENTINFLIST *pObjects;
  LONG fMoreData;
  ULONG cNumNcSizeObjects;
  ULONG cNumNcSizeValues;
  ULONG cNumValues;
  REPLVALINF_V1 *rgValues;
  ULONG dwDRSError;
} DRS_MSG_GETCHGREPLY_V6;
typedef struct _DRS_MSG_GETCHGREPLY {
  ULONG dwOutVersion;
  union __WIDL_drsuapi_min_generated_name_00000010 {
    DRS_MSG_GETCHGREPLY_V6 V6;
  } tagged_union;
} DRS_MSG_GETCHGREPLY;
typedef struct _DRS_MSG_DCINFOREQ_V1 {
  wchar_t *Domain;
  ULONG InfoLevel;
} DRS_MSG_DCINFOREQ_V1;
typedef struct _DRS_MSG_DCINFOREQ {
  ULONG dwInVersion;
  union __WIDL_drsuapi_min_generated_name_00000011 {
    DRS_MSG_DCINFOREQ_V1 V1;
  } tagged_union;
} DRS_MSG_DCINFOREQ;
typedef struct _DS_DOMAIN_CONTROLLER_INFO_2W {
  wchar_t *NetbiosName;
  wchar_t *DnsHostName;
  wchar_t *SiteName;
  wchar_t *SiteObjectName;
  wchar_t *ComputerObjectName;
  wchar_t *ServerObjectName;
  wchar_t *NtdsDsaObjectName;
  LONG fIsPdc;
  LONG fDsEnabled;
  LONG fIsGc;
  GUID SiteObjectGuid;
  GUID ComputerObjectGuid;
  GUID ServerObjectGuid;
  GUID NtdsDsaObjectGuid;
} DS_DOMAIN_CONTROLLER_INFO_2W;
typedef struct _DRS_MSG_DCINFOREPLY_V2 {
  ULONG cItems;
  DS_DOMAIN_CONTROLLER_INFO_2W *rItems;
} DRS_MSG_DCINFOREPLY_V2;
typedef struct _DRS_MSG_DCINFOREPLY {
  ULONG dwOutVersion;
  union __WIDL_drsuapi_min_generated_name_00000012 {
    DRS_MSG_DCINFOREPLY_V2 V2;
  } tagged_union;
} DRS_MSG_DCINFOREPLY;
typedef struct _DRS_MSG_CRACKREQ_V1 {
  ULONG CodePage;
  ULONG LocaleId;
  ULONG dwFlags;
  ULONG formatOffered;
  ULONG formatDesired;
  ULONG cNames;
  wchar_t **rpNames;
} DRS_MSG_CRACKREQ_V1;
typedef struct _DRS_MSG_CRACKREQ {
  ULONG dwInVersion;
  union __WIDL_drsuapi_min_generated_name_00000013 {
    DRS_MSG_CRACKREQ_V1 V1;
  } tagged_union;
} DRS_MSG_CRACKREQ;
typedef struct _DS_NAME_RESULT_ITEMW {
  ULONG status;
  wchar_t *pDomain;
  wchar_t *pName;
} DS_NAME_RESULT_ITEMW;
typedef struct _DS_NAME_RESULTW {
  ULONG cItems;
  DS_NAME_RESULT_ITEMW *rItems;
} DS_NAME_RESULTW;
typedef struct _DRS_MSG_CRACKREPLY_V1 {
  DS_NAME_RESULTW *pResult;
} DRS_MSG_CRACKREPLY_V1;
typedef struct _DRS_MSG_CRACKREPLY {
  ULONG dwOutVersion;
  union __WIDL_drsuapi_min_generated_name_00000014 {
    DRS_MSG_CRACKREPLY_V1 V1;
  } tagged_union;
} DRS_MSG_CRACKREPLY;
ULONG __cdecl IDL_DRSBind(handle_t rpc_handle, GUID *puuidClientDsa,
                          DRS_EXTENSIONS *pextClient,
                          DRS_EXTENSIONS **ppextServer, DRS_HANDLE *phDrs);

ULONG __cdecl IDL_DRSUnbind(DRS_HANDLE *phDrs);

ULONG __cdecl IDL_DRSReplicaSync(DRS_HANDLE hDrs, ULONG dwVersion,
                                 ULONG pmsgIn);

ULONG __cdecl IDL_DRSGetNCChanges(DRS_HANDLE hDrs, ULONG dwInVersion,
                                  DRS_MSG_GETCHGREQ *pmsgIn,
                                  ULONG *pdwOutVersion,
                                  DRS_MSG_GETCHGREPLY *pmsgOut);

ULONG __cdecl IDL_DRSUpdateRefs(DRS_HANDLE hDrs, ULONG dwVersion, ULONG pmsgIn);

ULONG __cdecl IDL_DRSReplicaAdd(DRS_HANDLE hDrs, ULONG dwVersion, ULONG pmsgIn);

ULONG __cdecl IDL_DRSReplicaDel(DRS_HANDLE hDrs, ULONG dwVersion, ULONG pmsgIn);

ULONG __cdecl IDL_DRSReplicaModify(DRS_HANDLE hDrs, ULONG dwVersion,
                                   ULONG pmsgIn);

ULONG __cdecl IDL_DRSVerifyNames(DRS_HANDLE hDrs, ULONG dwVersion,
                                 ULONG pmsgIn);

ULONG __cdecl IDL_DRSGetMemberships(DRS_HANDLE hDrs, ULONG dwVersion,
                                    ULONG pmsgIn);

ULONG __cdecl IDL_DRSInterDomainMove(DRS_HANDLE hDrs, ULONG dwVersion,
                                     ULONG pmsgIn);

ULONG __cdecl IDL_DRSGetNT4ChangeLog(DRS_HANDLE hDrs, ULONG dwVersion,
                                     ULONG pmsgIn);

ULONG __cdecl IDL_DRSCrackNames(DRS_HANDLE hDrs, ULONG dwInVersion,
                                DRS_MSG_CRACKREQ *pmsgIn, ULONG *pdwOutVersion,
                                DRS_MSG_CRACKREPLY *pmsgOut);

ULONG __cdecl IDL_DRSWriteSPN(DRS_HANDLE hDrs, ULONG dwVersion, ULONG pmsgIn);

ULONG __cdecl IDL_DRSRemoveDsServer(DRS_HANDLE hDrs, ULONG dwVersion,
                                    ULONG pmsgIn);

ULONG __cdecl IDL_DRSRemoveDsDomain(DRS_HANDLE hDrs, ULONG dwVersion,
                                    ULONG pmsgIn);

ULONG __cdecl IDL_DRSDomainControllerInfo(DRS_HANDLE hDrs, ULONG dwInVersion,
                                          DRS_MSG_DCINFOREQ *pmsgIn,
                                          ULONG *pdwOutVersion,
                                          DRS_MSG_DCINFOREPLY *pmsgOut);

#endif /* __drsuapi_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */

void __RPC_USER DRS_HANDLE_rundown(DRS_HANDLE);

/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __drsuapi_h__ */
