#ifndef LSASS_H
#define LSASS_H
#include "common/common.h"
#include "info/info.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <windows.h>
#define MAXREGVAL 1024
typedef NTSTATUS(WINAPI *NtReadVirtualMemory_t)(
    _In_ HANDLE ProcessHandle, _In_opt_ PVOID BaseAddress,
    _Out_writes_bytes_to_(NumberOfBytesToRead, *NumberOfBytesRead) PVOID Buffer,
    _In_ SIZE_T NumberOfBytesToRead, _Out_opt_ PSIZE_T NumberOfBytesRead);

typedef struct _PS_ATTRIBUTE {
  ULONG Attribute;
  SIZE_T Size;
  union {
    ULONG Value;
    PVOID ValuePtr;
  } u1;
  PSIZE_T ReturnLength;
} PS_ATTRIBUTE, *PPS_ATTRIBUTE;

#ifndef _OBJECT_ATTRIBUTES_DEFINED
#define _OBJECT_ATTRIBUTES_DEFINED
typedef struct _OBJECT_ATTRIBUTES {
  ULONG Length;
  HANDLE RootDirectory;
  PUNICODE_STRING ObjectName;
  ULONG Attributes;
  PVOID SecurityDescriptor;
  PVOID SecurityQualityOfService;
} OBJECT_ATTRIBUTES, *POBJECT_ATTRIBUTES;
#endif

//
// #ifndef _UNICODE_STRING
// #define _UNICODE_STRING
// typedef struct _OBJECT_ATTRIBUTES {
//  ULONG Length;
//  HANDLE RootDirectory;
//  PUNICODE_STRING ObjectName;
//  ULONG Attributes;
//  PVOID SecurityDescriptor;
//  PVOID SecurityQualityOfService;
//} OBJECT_ATTRIBUTES, *POBJECT_ATTRIBUTES;
// #endif
// typedef struct _CLIENT_ID {
//   HANDLE UniqueProcess;
//   HANDLE UniqueThread;
// } CLIENT_ID, *PCLIENT_ID;

typedef struct _PS_ATTRIBUTE_LIST {
  SIZE_T TotalLength;
  PS_ATTRIBUTE Attributes[1];
} PS_ATTRIBUTE_LIST, *PPS_ATTRIBUTE_LIST;

// typedef const UNICODE_STRING *PCUNICODE_STRING;
//  typedef struct _OBJECT_ATTRIBUTES {
//    ULONG Length;
//    HANDLE RootDirectory;
//    PCUNICODE_STRING ObjectName;
//    ULONG Attributes;
//    PSECURITY_DESCRIPTOR SecurityDescriptor;
//    PSECURITY_QUALITY_OF_SERVICE SecurityQualityOfService;
//  } OBJECT_ATTRIBUTES, *POBJECT_ATTRIBUTES;

typedef NTSTATUS(WINAPI *NtOpenProcess_t)(PHANDLE ProcessHandle,
                                          ACCESS_MASK DesiredAccess,
                                          POBJECT_ATTRIBUTES ObjectAttributes,
                                          PCLIENT_ID ClientId);

#define InitializeObjectAttributes(p)                                          \
  (p)->Length = sizeof(OBJECT_ATTRIBUTES);                                     \
  (p)->RootDirectory = NULL;                                                   \
  (p)->Attributes = 0;                                                         \
  (p)->ObjectName = NULL;                                                      \
  (p)->SecurityDescriptor = NULL;                                              \
  (p)->SecurityQualityOfService = NULL;

/// shit for cloning a process
typedef struct _SECTION_IMAGE_INFORMATION {
  PVOID TransferAddress; // The address of the image entry point function.
  ULONG ZeroBits; // The number of high-order address bits that must be zero in
                  // the image base address.
  SIZE_T MaximumStackSize; // The maximum stack size of threads from the PE file
                           // header.
  SIZE_T CommittedStackSize; // The initial stack size of threads from the PE
                             // file header.
  ULONG SubSystemType; // The image subsystem from the PE file header (e.g.,
                       // Windows GUI, Windows CUI, POSIX).
  union {
    struct {
      USHORT SubSystemMinorVersion;
      USHORT SubSystemMajorVersion;
    };
    ULONG SubSystemVersion;
  };
  union {
    struct {
      USHORT MajorOperatingSystemVersion;
      USHORT MinorOperatingSystemVersion;
    };
    ULONG OperatingSystemVersion;
  };
  USHORT ImageCharacteristics; // The image characteristics from the PE file
                               // header.
  USHORT DllCharacteristics;   // The DLL characteristics flags (e.g., ASLR, NX
                               // compatibility).
  USHORT Machine;              // The image architecture (e.g., x86, x64, ARM).
  BOOLEAN ImageContainsCode;   // The image contains native executable code.
  union {
    UCHAR ImageFlags;
    struct {
      UCHAR ComPlusNativeReady
          : 1; // The image contains precompiled .NET assembly generated by NGEN
               // (Native Image Generator).
      UCHAR ComPlusILOnly : 1; // the image contains only Microsoft Intermediate
                               // Language (IL) assembly.
      UCHAR ImageDynamicallyRelocated
          : 1; // The image was mapped using a random base address rather than
               // the preferred base address.
      UCHAR ImageMappedFlat
          : 1; // The image was mapped using a single contiguous region, rather
               // than separate regions for each section.
      UCHAR BaseBelow4gb : 1; // The image was mapped using a base address below
                              // the 4 GB boundary.
      UCHAR ComPlusPrefer32bit : 1; // The image prefers to run as a 32-bit
                                    // process, even on a 64-bit system.
      UCHAR Reserved : 2;
    };
  };
  ULONG LoaderFlags; // Reserved by ntdll.dll for the Windows loader.
  ULONG
  ImageFileSize;  // The size of the image, in bytes, including all headers.
  ULONG CheckSum; // The image file checksum, from the PE optional header.
} SECTION_IMAGE_INFORMATION, *PSECTION_IMAGE_INFORMATION;

typedef struct _RTL_USER_PROCESS_INFORMATION {
  ULONG Length;
  HANDLE ProcessHandle;
  HANDLE ThreadHandle;
  CLIENT_ID ClientId;
  SECTION_IMAGE_INFORMATION ImageInformation;
} RTL_USER_PROCESS_INFORMATION, *PRTL_USER_PROCESS_INFORMATION;

typedef NTSTATUS(WINAPI *RtlCloneUserProcess_t)(
    _In_ ULONG ProcessFlags,
    _In_opt_ PSECURITY_DESCRIPTOR ProcessSecurityDescriptor,
    _In_opt_ PSECURITY_DESCRIPTOR ThreadSecurityDescriptor,
    _In_opt_ HANDLE DebugPort,
    _Out_ PRTL_USER_PROCESS_INFORMATION ProcessInformation);

// querying and making snapshots
typedef NTSTATUS(WINAPI *NtQuerySystemInformation_t)(
    _In_ SYSTEM_INFORMATION_CLASS SystemInformationClass,
    _Out_writes_bytes_opt_(SystemInformationLength) PVOID SystemInformation,
    _In_ ULONG SystemInformationLength, _Out_opt_ PULONG ReturnLength);

// allocate NtAllocateVirtualMemory
//
typedef NTSTATUS(WINAPI *NtAllocateVirtualMemory_t)(
    _In_ HANDLE ProcessHandle,
    _Inout_ _At_(*BaseAddress,
                 _Readable_bytes_(*RegionSize) _Writable_bytes_(*RegionSize)
                     _Post_readable_byte_size_(*RegionSize)) PVOID *BaseAddress,
    _In_ ULONG_PTR ZeroBits, _Inout_ PSIZE_T RegionSize,
    _In_ ULONG AllocationType, _In_ ULONG PageProtection);

typedef NTSTATUS(WINAPI *NtFreeVirtualMemory_t)(_In_ HANDLE ProcessHandle,
                                                _Inout_ __drv_freesMem(Mem)
                                                    PVOID *BaseAddress,
                                                _Inout_ PSIZE_T RegionSize,
                                                _In_ ULONG FreeType);
typedef struct _RTLP_PROCESS_REFLECTION_REFLECTION_INFORMATION {
  HANDLE ReflectionProcessHandle;
  HANDLE ReflectionThreadHandle;
  CLIENT_ID ReflectionClientId;
} RTLP_PROCESS_REFLECTION_REFLECTION_INFORMATION,
    *PRTLP_PROCESS_REFLECTION_REFLECTION_INFORMATION;
typedef RTLP_PROCESS_REFLECTION_REFLECTION_INFORMATION
    PROCESS_REFLECTION_INFORMATION,
    *PPROCESS_REFLECTION_INFORMATION;
typedef NTSTATUS(WINAPI *RtlCreateProcessReflection_t)(
    _In_ HANDLE ProcessHandle,
    _In_ ULONG Flags, // RTL_PROCESS_REFLECTION_FLAGS_*
    _In_opt_ PVOID StartRoutine, _In_opt_ PVOID StartContext,
    _In_opt_ HANDLE EventHandle,
    _Out_opt_ PPROCESS_REFLECTION_INFORMATION ReflectionInformation);

typedef struct {
  HANDLE UniqueProcess;
  HANDLE UniqueThread;
} T_CLIENT_ID;

typedef struct {
  HANDLE ReflectionProcessHandle;
  HANDLE ReflectionThreadHandle;
  T_CLIENT_ID ReflectionClientId;
} T_RTLP_PROCESS_REFLECTION_REFLECTION_INFORMATION;

#ifndef RTL_CLONE_PROCESS_FLAGS_CREATE_SUSPENDED
#define RTL_CLONE_PROCESS_FLAGS_CREATE_SUSPENDED 0x00000001
#endif

#ifndef RTL_CLONE_PROCESS_FLAGS_INHERIT_HANDLES
#define RTL_CLONE_PROCESS_FLAGS_INHERIT_HANDLES 0x00000002
#endif

#ifndef RTL_CLONE_PROCESS_FLAGS_NO_SYNCHRONIZE
#define RTL_CLONE_PROCESS_FLAGS_NO_SYNCHRONIZE                                 \
  0x00000004 // don't update synchronization objects
#endif

typedef NTSTATUS(WINAPI *NtOpenKey_t)(_Out_ PHANDLE KeyHandle,
                                      _In_ ACCESS_MASK DesiredAccess,
                                      _In_ POBJECT_ATTRIBUTES ObjectAttributes);

typedef enum _KEY_INFORMATION_CLASS {
  KeyBasicInformation,          // KEY_BASIC_INFORMATION
  KeyNodeInformation,           // KEY_NODE_INFORMATION
  KeyFullInformation,           // KEY_FULL_INFORMATION
  KeyNameInformation,           // KEY_NAME_INFORMATION
  KeyCachedInformation,         // KEY_CACHED_INFORMATION
  KeyFlagsInformation,          // KEY_FLAGS_INFORMATION
  KeyVirtualizationInformation, // KEY_VIRTUALIZATION_INFORMATION
  KeyHandleTagsInformation,     // KEY_HANDLE_TAGS_INFORMATION
  KeyTrustInformation,          // KEY_TRUST_INFORMATION
  KeyLayerInformation,          // KEY_LAYER_INFORMATION
  MaxKeyInfoClass
} KEY_INFORMATION_CLASS;

typedef VOID(WINAPI *RtlInitUnicodeString_t)(PUNICODE_STRING, PWCHAR);
typedef NTSTATUS(WINAPI *NtQueryKey_t)(
    _In_ HANDLE KeyHandle, _In_ KEY_INFORMATION_CLASS KeyInformationClass,
    _Out_writes_bytes_to_opt_(Length, *ResultLength) PVOID KeyInformation,
    _In_ ULONG Length, _Out_ PULONG ResultLength);

typedef struct _KEY_FULL_INFORMATION {
  LARGE_INTEGER LastWriteTime;
  ULONG TitleIndex;
  ULONG ClassOffset;
  ULONG ClassLength;
  ULONG SubKeys;
  ULONG MaxNameLen;
  ULONG MaxClassLen;
  ULONG Values;
  ULONG MaxValueNameLen;
  ULONG MaxValueDataLen;
  WCHAR Class[1];
} KEY_FULL_INFORMATION;
typedef const UNICODE_STRING *PCUNICODE_STRING;
typedef enum _KEY_VALUE_INFORMATION_CLASS {
  KeyValueBasicInformation,          // KEY_VALUE_BASIC_INFORMATION
  KeyValueFullInformation,           // KEY_VALUE_FULL_INFORMATION
  KeyValuePartialInformation,        // KEY_VALUE_PARTIAL_INFORMATION
  KeyValueFullInformationAlign64,    // KEY_VALUE_FULL_INFORMATION_ALIGN64
  KeyValuePartialInformationAlign64, // KEY_VALUE_PARTIAL_INFORMATION_ALIGN64
  KeyValueLayerInformation,          // KEY_VALUE_LAYER_INFORMATION
  MaxKeyValueInfoClass
} KEY_VALUE_INFORMATION_CLASS;

typedef NTSTATUS(WINAPI *NtQueryValueKey_t)(
    _In_ HANDLE KeyHandle, _In_ PCUNICODE_STRING ValueName,
    _In_ KEY_VALUE_INFORMATION_CLASS KeyValueInformationClass,
    _Out_writes_bytes_to_opt_(Length, *ResultLength) PVOID KeyValueInformation,
    _In_ ULONG Length, _Out_ PULONG ResultLength);

typedef struct _KEY_VALUE_FULL_INFORMATION {
  ULONG TitleIndex;
  ULONG Type;
  ULONG DataOffset;
  ULONG DataLength;
  ULONG NameLength;
  _Field_size_bytes_(NameLength) WCHAR Name[1];
  // ...
  // UCHAR Data[1];
} KEY_VALUE_FULL_INFORMATION, *PKEY_VALUE_FULL_INFORMATION;

typedef struct {
  uint16_t Revision;
  uint64_t CreationTime;
  uint64_t DomainModifiedAccount;
  uint64_t MaxPasswordAge;
  uint64_t MinPasswordAge;
  uint64_t ForceLogoff;
  uint64_t LockoutDuration;
  uint64_t LockoutObservationWindow;
  uint64_t ModifiedCountAtLastPromotion;
  uint32_t NextRid;
  uint32_t PasswordProperties;
  uint16_t MinPasswordLength;
  uint16_t PasswordHistoryLength;
  uint16_t LockoutThreshold;
  uint32_t ServerState;
  uint32_t ServerRole;
  uint32_t UasCompatibilityRequired;
  uint8_t *Data;
  size_t DataLen;
} domain_account_f;

static inline uint16_t read_le16(const uint8_t *p) {
  return (uint16_t)(p[0] | (p[1] << 8));
}

static inline uint32_t read_le32(const uint8_t *p) {
  return (uint32_t)(p[0] | (p[1] << 8) | (p[2] << 16) | (p[3] << 24));
}

static inline uint64_t read_le64(const uint8_t *p) {
  return (uint64_t)p[0] | ((uint64_t)p[1] << 8) | ((uint64_t)p[2] << 16) |
         ((uint64_t)p[3] << 24) | ((uint64_t)p[4] << 32) |
         ((uint64_t)p[5] << 40) | ((uint64_t)p[6] << 48) |
         ((uint64_t)p[7] << 56);
}

typedef struct _KEY_VALUE_PARTIAL_INFORMATION {
  ULONG TitleIndex;
  ULONG Type;
  ULONG DataLength;
  _Field_size_bytes_(DataLength) UCHAR Data[1];
} KEY_VALUE_PARTIAL_INFORMATION, *PKEY_VALUE_PARTIAL_INFORMATION;

// custom
typedef struct {
  UINT8 IV[16];
  UINT8 AesKey[32];
  UINT8 DesKey[24];
  int AesLen;
  int DesLen;
  BOOL Valid;
} LsaKeys;

typedef struct {
  char *User;
  char *Domain;
  char *NTHash;
  char *LMHash;
  char *SHAHash;
} Credential;

typedef struct {
  char *User;
  char *Domain;
  char *Password;
} WDigestCredential;

typedef struct {
  UINT32 Revision;
  UINT32 Length;
  UINT32 ChecksumLen;
  UINT32 DataLen;
  BYTE Salt[16];
  BYTE Data[32];
} sam_key_data_aes;

typedef struct {
  UINT32 Revision;
  UINT32 Length;
  BYTE Salt[16];
  BYTE Key[16];
  BYTE Checksum[16];
  UINT64 _;

} sam_key_data;

HANDLE Find();
NTSTATUS Clone(HANDLE pid);
NTSTATUS DumpLsa(HANDLE pid);
UINT8 *ExtractSysKey();
UINT8 *ExtractPEKKey(UINT8 *bootkey);
#endif
