name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: x86_64-pc-windows-msvc

    - name: Install xwin
      run: cargo install xwin --locked

    - name: Splat xwin (download SDK and CRT headers)
      run: xwin --accept-license splat --output ~/.xwin

    - name: Configure Cargo for xwin
      run: |
          mkdir -p .cargo
          cat << 'EOF' > .cargo/config.toml
          [target.x86_64-pc-windows-msvc]
          linker = "rust-lld"
          rustflags = [
              "-L", "native=/home/runner/.xwin/crt/lib/x86_64",
              "-L", "native=/home/runner/.xwin/sdk/lib/ucrt/x86_64",
              "-L", "native=/home/runner/.xwin/sdk/lib/um/x86_64",
          ]
          EOF
    - name: Install LLVM
      run: |
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 18

    - name: Install dependencies
      run: make

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-binary
        path: ./build/munchy.exe
        
